### ISSUE TITLE
Proposal for even simpler sampling controls

### ISSUE THREAD

**Issue by bsavery** [prman-pixar/RenderManForBlender#121]
In the vein of making the controls easy for beginner users and then allowing them to go more advanced, I'm proposing making the sampling panel even more simple in "Easy mode".

Here's how we could do it:  
![screen shot 2015-08-25 at 11 42 45 am](https://cloud.githubusercontent.com/assets/1892220/9475918/85f29d08-4b1e-11e5-9195-bd3f7723e3af.png)
![screen shot 2015-08-25 at 11 42 58 am](https://cloud.githubusercontent.com/assets/1892220/9475919/85f40fbc-4b1e-11e5-898c-807ca3d19b12.png)
![screen shot 2015-08-25 at 11 43 12 am](https://cloud.githubusercontent.com/assets/1892220/9475920/85f43b68-4b1e-11e5-826b-c10ced0836d9.png)

The render type would change integrators and settings like caustics, etc.  Quality/Time slider would drive the max samples and pixel variance.

Vray does something similar:
https://www.youtube.com/watch?v=buTEc5mrURg

**Comment by bsavery** [comment]
Thoughts?

**Comment by jdent02** [comment]
Looks promising.  It will certainly help make RenderMan a bit less scary for people.  Actually those settings would make it more straightforward to use than Cycles.....

Only snag I could see is the numbers in the Quality/Time slider.  It's possible some might associate that with actual time (minutes, etc....) instead of a 'quality percentage'.  not sure if you can really get around this though, it's just nit picking.

**Comment by bsavery** [comment]
Certainly could be labeled however you want.  Ideally, you'd like to give a time "estimate" for a given quality level.   I have some ideas how to do that...

**Comment by jdent02** [comment]
That'd be interesting to see.  I'll admit I'm really curious how you would tackle that.

**Comment by mifth** [comment]
Actually i see no point in this. There are only 4 values in general.
I would spend more time for viewport textures and shaders display.
Also, material nodes need more love i think.

**Comment by bsavery** [comment]
Its aimed at someone with less experience than you.  What do you mean by
"material nodes need more love".

On Tue, Aug 25, 2015 at 11:39 PM, mifth <notifications@github.com> wrote:

> Actually i see no point in this. There are only 4 values in general.
> I would spend more time for viewport textures and shaders display.
> Also, material nodes need more love i think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/121#issuecomment-134859793>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by mifth** [comment]
PrPatterns are too big and i think it could b splitted to more groups like in Cycles.
Like:
Texture
Color
Vector
etc.

![cache3](https://cloud.githubusercontent.com/assets/2251298/9497428/8e44311a-4c1d-11e5-884e-9fc2526aea32.png)

**Comment by mifth** [comment]
Also, I did not find RGB Curves node which is super cool for RGBA tweaks. Is it possible to add it?

![cache3](https://cloud.githubusercontent.com/assets/2251298/9497526/06a39808-4c1e-11e5-9566-1bbfb4302852.png)

**Comment by bsavery** [comment]
You bring up a good point with the categories.  I'm going to split that to another issue to keep this discussion on track.  RgbCurves might be a bit more difficult but let me think about it.  It's basically a spline...

**Comment by jdent02** [comment]
Brian,
Have you thought about this one further?  My list of projects is kinda bare so I'd be happy to tackle it.
