### ISSUE TITLE
Replace all non -ascii characters in object names 

### ISSUE THREAD

**Issue by bsavery** [prman-pixar/RenderManForBlender#399]
accents and such for object names screw up RenderMan.  There are a bunch of places they would need to change but we could substitute blanks for them.

**Comment by bsavery** [comment]
http://stackoverflow.com/questions/8689795/how-can-i-remove-non-ascii-characters-but-leave-periods-and-spaces-using-python

**Comment by jdent02** [comment]
It's just the object names with this issue right?  I'm assuming it would also include the meshes they're attached to?

**Comment by bsavery** [comment]
Any names of things that go into rib really.  Meshes, materials, objects, lamps.

**Comment by bsavery** [comment]
Nodes.  Kinda annoying but it would have to be "all the things"
