### ISSUE TITLE
Add preview command to alf files

### ISSUE THREAD

**Issue by bsavery** [prman-pixar/RenderManForBlender#431]
-preview {launch_expr}
launches an external application in the same manner as -chaser, however this version activates the launching button before the commands have completed.

https://renderman.pixar.com/resources/current/tractor/scriptingOperators.html

**Comment by earlywill** [comment]
I've had a go at this, although I'm doing a bit of string.replace which is likely to be fragile.

First replace is to fix backslashes to forward slashes.
Second replace is to convert rib to exr (this doesn't work with denoise)
Third is to replace variance with filtered.

Still working on it. This is what I've got

```
Task {Frame 1} -serialsubtasks 1 -subtasks {
			Task {Frame 1 textures} -serialsubtasks 0 -subtasks {
			}
			Task {Render frame 1} -cmds {
				RemoteCmd -service {PixarRender} {prman -progress -cwd "C:/tmp/renderman_for_blender/rman_metadata" -t:-1 -loglevel 4 -checkpoint 1m,1m "C:/tmp/renderman_for_blender/rman_metadata\Scene.0001.rib"}
			} -preview {it "C:/tmp/renderman_for_blender/rman_metadata/Scene.0001.variance.exr"}
			Task {Denoise frame 1} -cmds {
				RemoteCmd -service {PixarRender} {denoise --override gpuIndex 0 -- "C:/tmp/renderman_for_blender/rman_metadata\images\Scene.0001.variance.exr"}
			} -preview {it "C:/tmp/renderman_for_blender/rman_metadata/images/Scene.0001.filtered.exr"}
		}
```
