### ISSUE TITLE
material node group doesn't forward color data

### ISSUE THREAD

**Issue by charleshetier** [prman-pixar/RenderManForBlender#449]
Here is a material node setup:
**PxrTexture -> PxrDiffuse -> PRMan Material**

This basic setup works very well.

Now, if I wrap PxrDiffuse within a node group (**PxrTexture -> Group -> PRMan Material**),
the image texture is not taken into account anymore.

Also I set a red diffuse color, Suzanne is gray in this case:
![untitled](https://cloud.githubusercontent.com/assets/8912998/22655011/fc10c83a-ec8e-11e6-9cb7-897835b37de9.png)

![untitled](https://cloud.githubusercontent.com/assets/8912998/22655076/35bddc44-ec8f-11e6-93d6-21df0da96f9e.png)

Few checks:
* If I unplug the texture from the group node and set manually a color, the color is not taken into account.
* If I force the color of the PxrDiffuse in the group (unpluging the input node), the color is set properly.

I have tried several things, but each time I am trying to factorize with a group, the input seems not to be taken into account. I am missing something?

Thanks a lot

Charles HETIER

**Comment by bsavery** [comment]
I'll take a look when I get a chance.

**Comment by charleshetier** [comment]
Thank you. Thanks also for this amazing work, this is very exciting. I am currently studying doing my future works with Renderman on blender. I really need the ability to factorize my shader, but appart from that, the plugin is amazingly comprehensive.

By the way I am a professional developper. Sadly not in python, but maybe I could help especially for this issue with some few inputs. Is there a little documentation I could read to help getting in the project architecture?

regards

**Comment by jdent02** [comment]
There isn't much in the way of official code documentation for the exporter, outside of comments in the code itself (but those are lacking).  There's a full refactor of the exporter being put together and one of the goals there is to better document what everything's doing.

As far as the existing exporter the best way to learn it is to just poke around in the modules and see how they connect to each other.

**Comment by charleshetier** [comment]
Thank you for these inputs

**Comment by bsavery** [comment]
If you're interested take a look at the 21.3 branch where the refactor is happening.  Devel notes there.

https://github.com/bsavery/PRMan-for-Blender/tree/devel_21.3

**Comment by charleshetier** [comment]
Just to say I clearly won't have enought time to investigate into the code.
Really wanted to, but there are too much things I need to learn on blender sources first. Thanks anyway for taking time to provide me some few inputs.
