### ISSUE TITLE
auto smooth won't render

### ISSUE THREAD

**Issue by boboalice** [prman-pixar/RenderManForBlender#480]
the "auto smooth" option in object data, won't render.

![autos](https://cloud.githubusercontent.com/assets/27031391/25061434/068239e2-21bf-11e7-8c4b-2bb16773c962.png)

blend file:
http://s000.tinyupload.com/download.php?file_id=05150720385018564388&t=0515072038501856438872655

**Comment by bsavery** [comment]
I'm not sure.  I think that controls the normals in the blender mesh.  We're just rendering the normals we get from Blender.
