### ISSUE TITLE
IPR doesn't start

### ISSUE THREAD

**Issue by ChameleonScales** [prman-pixar/RenderManForBlender#520]
I get these errors when starting IPR :
```
R90007 {SEVERE}  DisplayWindow failed to send display data (System Error: Broken pipe)
R56005 {SEVERE}  Renderer completing shutdown request. (System Error: Broken pipe)
```
Specs :
Linux Manjaro x64
RenderManProServer-21.4

Rendering works fine though.

**Comment by bsavery** [comment]
Does Rendering to "IT" work, or just back to blender?  The reason I ask is, the "IT" program might not be starting correctly when you start IPR.

**Comment by ChameleonScales** [comment]
Only back to Blender.
When I select IT I get :
```
PRMan: R90011 {SEVERE}  Can't open display image /tmp/renderman_for_blender/untitled/images/Scene.0001.it (System Error: Connection refused)
```

**Comment by bsavery** [comment]
That's weird, most don't have an issue with "IT" auto starting.  You can start "IT" manually from the command line by setting RMANTREE=/opt/pixar/RenderManProServer-21.4/ and then running 
$RMANTREE/bin/it

**Comment by ChameleonScales** [comment]
Not sure I did it right but even doing :
```
cd /opt/pixar/RenderManProServer-21.4/bin/
./it
```
gives :
`Segmentation fault (core dumped)`

**Comment by ChameleonScales** [comment]
is it normal that it doesn't work if I use this previous command instead of using the env. variable ?

**Comment by ChameleonScales** [comment]
Today "it" decided to work when I run it directly for an unknown reason and after that it also worked when I used $RMANTREE/bin/it.
I don't like not knowing the reason but I'll cross my fingers for it to keep working everyday.
Thank you Brian
