### ISSUE TITLE
Spot light cone issues

### ISSUE THREAD

**Issue by AndreasReschGFX** [prman-pixar/RenderManForBlender#522]
Hi,

there's a bug with the spot light. Both the Blender settings and the Renderman settings for the cone shape and softness affect the light.

When I start IPR, the Blender cone settings are used for the light. As soon as I change the cone settings in the Renderman tab, the those settings are used and immediately updated in IPR. Whenever I stop and start IPR, the preview always will start with the Blender cone settings.
For the final rendering, Renderman always uses the Blender settings and ignores the Renderman settings.

This is hard to work with. While adjusting the Renderman cone settings while IPR is running, I can nicely watch the settings being updated in IPR. But the settings I decided on, will never be used in the final rendering.

I suggest to ditch the Blender cone settings tab all together.

Cheers,
Andreas

**Comment by bsavery** [comment]
I'll add a bit here. The reason the ipr updates with one and not the other is that currently shader updates are done via property update callbacks. Ie every RenderMan shader parameter has a callback function which if ipr is running does an instance edit for ipr. However we can't add these callbacks to built in properties like the cone angle. The reason we wanted to use the built in cone angle is updates the viewport cone angle visualizer. And for consistency with blender users. So as it works now we turn the built in cone angle into the cone angle parameter for the shader. Thinking about it now we could in that update function if the cone angle gets set update the built in one to get the visualization.

**Comment by AndreasReschGFX** [comment]
Thanks for the answer, Brian.

I can only comment from a user perspective and as it is now, it's confusing and annoying to use. Honestly - I can easily live without the cone representation in the viewport as long as the IPR and production rendering are the same. 

So I just wanted to "pin" the issue here.

Cheers,
Andreas

**Comment by bsavery** [comment]
I'm willing to make that change if @prman-pixar approves ;)
