### ISSUE TITLE
SyntaxError in Preset library

### ISSUE THREAD

**Issue by cryptozone** [prman-pixar/RenderManForBlender#523]
I get a stacktrace every time I try to load or assign any item from preset library(material etc.). The thumbnail previews are correctly displayed. I'm using Blender 2.78c(stable) and latest(stable) version of RenderManForBlender addon for PRMan 21.4.0. Operating system is maxOS Sierra. Everything else from the addon is working well on my machine. I've attached a screenshot below.

![screen shot 2017-06-30 at 05 13 32](https://user-images.githubusercontent.com/6691050/27719659-2800e6c4-5d54-11e7-9cae-d2349cde8fa3.png)

**Comment by jdent02** [comment]
What's the folder name for the add on?

**Comment by cryptozone** [comment]
I've attached a screenshot below with addon information including the full path to addon.

<img width="909" alt="screen shot 2017-06-30 at 06 11 50" src="https://user-images.githubusercontent.com/6691050/27720693-515fa396-5d5b-11e7-81e2-94e26ec77959.png">

**Comment by adminradio** [comment]
Mh, "Application Support" is  a macos system folder and should not be renamed!

Removing the dash from addon folder name will solve this issue!
See: https://renderman.pixar.com/forum/showthread.php?s=&threadid=34853

**Comment by cryptozone** [comment]
Thank you ! Removing the dash from addon name solved the problem.

**Comment by jdent02** [comment]
Well it's a good thing he didn't listen to me then :)
