### ISSUE TITLE
Can't use object-linked materials

### ISSUE THREAD

**Issue by Koopa1018** [prman-pixar/RenderManForBlender#524]
I've run into a problem using materials which are linked to the object.
Ordinarily, setting a material slot to "Object" lets me change a material on one object only, even if it's using a shared mesh.
Unfortunately, it doesn't seem to work when I'm using RenderMan--it just uses the material which is attached to the mesh data, completely ignoring the one attached to the object.

This seems like it could be seriously inconvenient to not have. I've already run into some problems, and I hope you fix it soon.

Thanks!

**Comment by bsavery** [comment]
I can see that being an issue, easy workaround though.  Strange this is the first time it came up though.
