### ISSUE TITLE
Black render result

### ISSUE THREAD

**Issue by DmytrPr** [prman-pixar/RenderManForBlender#525]
When i tried to render something i get error PRMan:Exited.
Console:ERROR: ('Export path [C:/tmp/renderman_for_blender/untitled/images/Scene.0001.exr] does not exist.',)

Blender and renderman installed in the default folders, licence is in the right folder.
I spent more than two hours trying to fix this problem.

**Comment by jdent02** [comment]
Are you using internal or external rendering?  Also, are you up to date with the exporter?

Sent from my iPhone

On Jul 9, 2017, at 2:03 PM, jezzgame <notifications@github.com<mailto:notifications@github.com>> wrote:


When i tried to render something i get error PRMan:Exited.
Console:ERROR: ('Export path [C:/tmp/renderman_for_blender/untitled/images/Scene.0001.exr] does not exist.',)

Blender and renderman installed in the default folders, licence is in the right folder.
I spent more than two hours trying to fix this problem.

**Comment by alastorid** [comment]
I got the same error, but I am using Linux version. After fixing up license issue it works great.
