### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by Paldesy** [prman-pixar/RenderManForBlender#528]
Hi I was wondering if the issue for 'Traceback Error When Enabling
#497 opened on May 12 by dustin2551' has been resolved ? I have the same issue. I have tried deleting the existing files and downloaded the latest zip to install but still get the same error. I am running it on a mac and have gone into library/application support/blender/2.78/Scripts/Addons folder and deleted the renderman for blender folder. Is there another area where I will find old files that are causing the conflict (if I understand the problem correctly)? Thanks for any help.
![traceback error](https://user-images.githubusercontent.com/30516224/28749446-db8d126c-750a-11e7-8ac3-9a5be16a8886.jpg)

**Comment by jdent02** [comment]
Did you download the latest version release or the latest master (downloading from the front page)?  The latest release version is several months old and I think that issue hadn't been solved at that point.

**Comment by Paldesy** [comment]
Hi @jdent02 
Thanks the master worked.
