### ISSUE TITLE
about renderman for blender the version

### ISSUE THREAD

**Issue by SunGodofworld** [prman-pixar/RenderManForBlender#530]
Mixer when it can support renderman21.5 version because I am using maya's renderman version is 21.5，I want to spare time to play a blender's renderman

**Comment by bsavery** [comment]
The latest branch supports 21.5

**Comment by SunGodofworld** [comment]
Why I see the latest release of the forum is 21.4

**Comment by SunGodofworld** [comment]
Why I see the latest release of the forum is 21.4

**Comment by jdent02** [comment]
Download the latest master from the main page.  The 21.4 release is several months out of date right now.
