### ISSUE TITLE
PxrRamp Single-User-Copy issue

### ISSUE THREAD

**Issue by AndreasReschGFX** [prman-pixar/RenderManForBlender#532]
Hello.

There's an issue with the PxrRamp node when you create a Single-User-Copy of a material. If you do so, and change the ramp colors of the new material, the PxrRamp node of the material that it was created from, changes as well. This only affects the ramp slider and none of the value fields.

Here's an example scene ... [http://www.andreasresch.at/upload/Renderman_Test_113.zip](url)

Cheers,
Andreas

**Comment by SimonStorlSchulke** [comment]
I have this problem too. Also when you delete a copy of the original PxrRamp, the original loses most of its attributes and becomes unusable.
A quick demonstation here: [https://youtu.be/TkTI2XS7eVM](https://youtu.be/TkTI2XS7eVM)
