### ISSUE TITLE
Export path does not exist

### ISSUE THREAD

**Issue by drichter79** [prman-pixar/RenderManForBlender#535]
I know this issue has been discussed before, but I couldn't find any working solution.

It seems the addon adds superfluous slashes to my addon defined paths.

The addon works as long as I don't use any renderman shaders. Then I get RenderMan: Exited

My defined path is (default):
C:/tmp/renderman_for_blender/{blend}

Addon makes out of it (error message system console):
![error](https://user-images.githubusercontent.com/31212481/29522464-77f021be-8689-11e7-885b-29a023f983c0.jpeg)

How can I get rid of all those wrong slashes and backslashes? The dots should also be problematic on windows, but removing them didnt help. Also other HDDs and paths didnt work. (Windows 10, Blender 2.78c). Renderman is installed at default path and also the .license file...

Greetings

**Comment by drichter79** [comment]
![error2](https://user-images.githubusercontent.com/31212481/29523210-8e6f8102-868c-11e7-8ff6-8e98fc33c694.jpeg)

New attempt - still not working and adding slashes...

**Comment by jdent02** [comment]
Double slashes isn't the issue.  For some reason the exporter does not appear to be creating the export directories.

Try rendering again and then take a look at your export directory to see what (if anything) was created.

**Comment by drichter79** [comment]
Okay, I tried default settings again and created Win10 admin this time.

Result:
![error3](https://user-images.githubusercontent.com/31212481/29527230-83e3bff8-8698-11e7-88b3-0c8a1c0e89bc.jpeg)

**Comment by jdent02** [comment]
I think this is more of a RenderMan issue as it looks like the proper export directories are being created.  Can you try deleting your renderman_for_blender directory in the tmp folder and run the export again just to make sure?

Next step would be running an external render to see if that works.

**Comment by drichter79** [comment]
Okay, maybe that is a Renderman prob.

Results of external render:

No Renderman Material:
![render1](https://user-images.githubusercontent.com/31212481/29567392-57eaa2d0-874d-11e7-8cf9-995f835b1e38.jpeg)

After add Renderman Node Tree on the material:
![render2](https://user-images.githubusercontent.com/31212481/29567396-5a8d3962-874d-11e7-9e5f-a3a43189f2c8.jpeg)
