### ISSUE TITLE
Missing Normals

### ISSUE THREAD

**Issue by renderdude** [prman-pixar/RenderManForBlender#538]
Attached is a small blender file that demonstrates the problem(s). 
- Start an IPR, and you'll have an image with a nice circular highlight. 
- Edit the 4x4 mesh. Select the right most column of faces and delete. We now have a 4x3 mesh.
- Restart the IPR (Why doesn't the IPR update after editing)
The highlight is now egg shaped.

If you compare the generated Mesh-MESH.rib files, the 4x4 mesh has a "facevarying N' parameter which is missing from the 4x3 mesh

Mark

[sub_sphere.blend.zip](https://github.com/prman-pixar/RenderManForBlender/files/1252334/sub_sphere.blend.zip)

**Comment by AndreasReschGFX** [comment]
Hello,

this might not be a Renderman issue. The situation is the same in Cycles.

![cycles_01](https://user-images.githubusercontent.com/23632045/29739887-95d564d2-8a49-11e7-99ee-bd4b195d5d6f.jpg)

Cheers,
Andreas
