### ISSUE TITLE
Viewport Color changes when changing node values

### ISSUE THREAD

**Issue by AndreasReschGFX** [prman-pixar/RenderManForBlender#539]
Hi,
here's a little bug. 

The Viewport Color of an object changes back to its default value whenever you adjust something in the Node Editor.

Here's a screencast of the issue ... http://www.andreasresch.at/upload/Renderman_ViewportColor_01.zip

Cheers,
Andreas

**Comment by adminradio** [comment]
Spotted the error here: [nodes.py -> RendermanShadingNode.update_mat()](https://github.com/prman-pixar/RenderManForBlender/blob/f24aeee3927f68426f69fbef21b418fdb462ecc5/nodes.py#L284)
