### ISSUE TITLE
Light linking doesn't work

### ISSUE THREAD

**Issue by AndreasReschGFX** [prman-pixar/RenderManForBlender#547]
Hello,

seems as if light linking doesn't work.

I've created all combinations of lights, light groups, objects, object groups. Nothing works. 

Here's a sample scene ... http://www.andreasresch.at/upload/Renderman_Test_120.zip

Cheers,
Andreas

**Comment by jdent02** [comment]
Are all the lights and objects unique?  As in nothing shares any datablocks or meshes?  I've found that the exporter doesn't like that.
