### ISSUE TITLE
Render To "Blender" Crashes Blender 2.79

### ISSUE THREAD

**Issue by jzazbert** [prman-pixar/RenderManForBlender#548]
When using the default render setting asking Renderman to render to Blender (instead of It), Blender 2.79 (release, RC1, RC2) crashes, and leaves this error at the command line:

Error: EXCEPTION_ACCESS_VIOLATION

I have tested this on both Windows 10 64bit and Linux Ubuntu 16.04 64 bit, and both have the same issue.

**Comment by bsavery** [comment]
What is your CPU type?

**Comment by jzazbert** [comment]
i7-7700k for the windows 10 machine, i7-4850mq for the linux machine. This also occurred on an older i7 960 running windows 7.

**Comment by Viduttam** [comment]
Hi Brian, I'm facing the same issue. Blender 2.79(latest release) crashes when "Render To" parameter is set to "Blender". I'm running on Windows 10 Intel Core i7 6700HQ

**Error: EXCEPTION_ACCESS_VIOLATION**

**Comment by stefvogel** [comment]
Hi Brain! Same here. Running on OSX 10.12.6, 2.5 GHz Intel Core i7, MacBook Pro (Retina, 15-inch, Mid 2015), 16 GB 1600 MHz DDR3, Intel Iris Pro 1536 MB.
When rendering with IPR it works but when rendering it normally it crashes.

Cheers!

**Comment by B-Train04** [comment]
Also here, I3-6100 and RX 460 2gb, Windows 10 Creators Update x64, 8gb DDR4 RAM.
Default cube and area lamp, rendering to "Blender" causes C2D

**Comment by Lightye** [comment]
Do see a couple of crashes with RIB-gen also when rendering via Tractor to It also. Blender 2.79. Can try to identify more what is going on.

**Comment by GJKrupa** [comment]
I'm seeing the same with RM 21.6 and Blender 2.79 on MacOS 10.13.2 (2016 15" MBP with TouchBar, 2.9GHz i7-6920HQ, Radeon Pro 450 2 GB).  Blender's crash log is attached...
[blender.crash.txt](https://github.com/prman-pixar/RenderManForBlender/files/1545489/blender.crash.txt)

**Comment by worellana** [comment]
Any update about this issue, I have the same crash on Windows 10 64 bits, i7-5500U CPU @ 2.40GHz, 8GB RAM, Blender 2.79 and Renderman 21.6

Error: EXCEPTION_ACCESS_VIOLATION

**Comment by f1vefour** [comment]
@worellana See b4aa6b4409f0a2f886486c60d10c4ca3f650096e

**Comment by worellana** [comment]
Thanks, @f1vefour that resolved the issue

**Comment by f1vefour** [comment]
@jzazbert this issue should be closed

**Comment by EddieSoloProjects** [comment]
No it is crashing on the Blender tutorial file for me from the Pixar site. It is Not Fixed at all...
