### ISSUE TITLE
Holdout not working properly

### ISSUE THREAD

**Issue by paristopolus** [prman-pixar/RenderManForBlender#550]
Hey Guys,

This is a variation on issue #372 
https://github.com/prman-pixar/RenderManForBlender/issues/372

For the life of me, I can't seem to get the holdouts to work properly.
I followed a tutorial on setting up the holdout using the collector, but each time only the alpha of the object in the scene gets rendered, not the ground contact shadows.
I've attached the file in case I'm just setting it up improperly.
I am using Blender 2.79 and the latest RenderManForBlender add-on.

The ground plane is added to the collector object group.
I activated the holdout flag in the "object" tab, and added a custom LPE AOV called "holdout"
The holdout LPE then has a custom string: 'color lpe:holdout;shadows;C[<.D'collector'><.S'collector'>]'

The tutorial I followed and embellished on:
https://vimeo.com/165352361

My file:
[MMTT_3DRender_06.zip](https://github.com/prman-pixar/RenderManForBlender/files/1319297/MMTT_3DRender_06.zip)

Any help would be greatly appreciated!

Thanks!

**Comment by Viduttam** [comment]
Hi there, I am running into the same issue and the holdout workflow mentioned in the above video does not seem to be working. Also there seems to be no other resources/mentions of the holdout workflow in Renderman for Blender on the rfB wiki.
However, I've figured out a workaround. Follow all the steps in the video and setup the AOVs. Next, **uncheck/deselect** the *holdout* option from the ground plane/floor object. And instead **set** the primary object/cube/teapot as a **Matte object**.
On rendering now, you should see the expected results in the Shadows AOV. 
I've tested this on Blender 2.79 and Renderman 21.5
Hope this helps!
Cheers!

**Comment by paristopolus** [comment]
Hey man, thanks for the tip!

As it turns out, I'm participating in the Teapot Challenge over at PIXAR and need to use the Holdout for qualifications. I was able to work around the wonkiness of the holdout implementation by using the sample filter system in the scene properties. I'll try your method too!

![shadowcatcher](https://user-images.githubusercontent.com/32145811/31282796-a8ebdb70-aa81-11e7-89a5-757455265d37.PNG)


Thanks!

**Comment by paristopolus** [comment]
Oh, and one other thing.
I like the shadow filter, because it allows me to use the holdout method, and because it provides an occluded image (ground with shadow), unoccluded (ground without shadow), and the alpha for the shadow itself. It checks all my boxes in that regard and it allows me to follow the rules for the challenge.

Thanks again!

**Comment by turtletennis** [comment]
Yeah, shadowcollector LPE which worked in 21.4 ( color lpe:shadowcollector ) doesn't work in 21.5 for me. The reflectioncollector LPE does still work in 21.5 though. ( color lpe:reflectioncollector ).

**Comment by MattRM2** [comment]
Hummm, a way to have the shadows and the reflections in the last Blender and renderman 21.5  ? 21.5 works well on Blender than Houdini 16.5... miss a big part in the pxrPathTracer... like depth for diffuse and specular lol

Thanks

ps : a little tutorial in this thread can be great ;) Viduttam, is it possible a little process here ? Want to do the Pixar challenge too :)

**Comment by MattRM2** [comment]
Oki, understood how to use the ShadowDilter, great !!! think work the same under Houdini 16.5 but not solve the depth for diffuse and specular lol

Thanks
