### ISSUE TITLE
Using ImagePlaneFilter does not automatically execute TXmake on the image

### ISSUE THREAD

**Issue by jzazbert** [prman-pixar/RenderManForBlender#551]
I've added an ImagePlaneFilter to an image (applied as either display or sample filters), in conjunction with a holdout object. When I render, I get two errors, and no background image.

RenderMan: R10043 {WARNING} ishouldnotexport, unknown or mismatched input parameter of PxrImageDisplayFilter (f2).
RenderMan: X00003 {WARNING} Plugin warning: PxrImageDisplayFilter: Could not acquire texture '8eb8745d-1fa9-4c98-b764-7de2e07a4db7_2.8817a110e71d3f5cad153957d0b77df5.tex'

It appears that txmake does not run to generate the texture. If I manually create the texture or add it to a pxrtexture node somewhere so that it gets generated, it renders properly. Even when it renders properly, I still get the first R10043 error.

--
Renderman for Blender 21.5 [Latest]
Blender 2.79
Windows 10 64bit, i7-7700k

**Comment by Lightye** [comment]
+1

**Comment by jdent02** [comment]
Yes TxMake does not run on filenames in the display filter.  If I get some time in the next week or so I'll take a look at adding that in.

**Comment by fxjeane** [comment]
I would be happy to look into this request. Do you have a quick pointer on what files to look into?
