### ISSUE TITLE
Selecting Image Texture from menu doesn't work in Cycles

### ISSUE THREAD

**Issue by Koopa1018** [prman-pixar/RenderManForBlender#554]
I still use Cycles most of the time. 
Oftentimes, when I'm building simple materials, I'll add the texture nodes from the Properties sidebar before going into the node editor. 
Ever since I installed the PRMan plugin (way back in 2.78 days), I've been unable to do this--when I try, it adds a RenderMan node instead (in 2.79 it's "PxrGeometricAOVs", but it was a different one that I can't recall back in 2.78).
This only occurs in the Properties window, not the node editor, so it's a minor inconvenience at most, but still....

**Comment by jdent02** [comment]
Yeah that's been that way for a while.  Brian was going to look into it but I don't think he found time.

**Comment by bsavery** [comment]
For the record, I claim most assuredly this is blender bug but the devs have disagreed.
