### ISSUE TITLE
UDIMs not working with Blender 2.79 and PRMAN 21.5?

### ISSUE THREAD

**Issue by Viduttam** [prman-pixar/RenderManForBlender#555]
Hi Guys,

I'm unable to get UDIMs to work in **PRMAN 21.5** and **Blender 2.79**

I have the below UV layout and using **\_MAPID\_** in the filename section and have set the **Atlas style to Mari**

The first row of udim uvs are the ones that get the texture applied correctly however the second row seems to have some garbled textures applied while all the other rows appear to have missing textures(pink color).

I have tried using .png and .tex but both yield the same result. Also tried appending a pxrManifold2D node just to be sure that it is using the UVs but nothing seems to be working.

The last image below is a test render from Substance Painter of the same asset with exactly the same UDIM layout which is how I'm expecting the render to look like.

![PRman render](http://i65.tinypic.com/2cfbqfa.jpg)
![udim layout](http://i67.tinypic.com/2ir6cew.jpg)
![shader](http://i68.tinypic.com/288xish.jpg)
![Substance painter render](http://i65.tinypic.com/dc6fdv.jpg)

**Comment by Viduttam** [comment]
Quick update ran tests with Blender 2.78c and PRMAN 21.5 and am unable to get the UDIMs to work. On going through the stats.xml only the first row of textures are being pulled over by the PRMAN (1001-1006) and no other texture is being fetched.

**Comment by earlywill** [comment]
I've had a go at addressing this. https://github.com/prman-pixar/RenderManForBlender/pull/559

You should have an object setting for choosing the flipV method. Although it's probably best to do this flip in PxrTexture.

**Comment by Viduttam** [comment]
Yup, Will's update has been merged with the latest code on github. Hence closing this issue!
Thanks
