### ISSUE TITLE
Denoising AOVs in Blender not work and where put importance sampling

### ISSUE THREAD

**Issue by MattRM2** [prman-pixar/RenderManForBlender#556]
Hi,

I found no ways to denoising AOVs in Blender and found no options to change sampling methode to importance.

I missed something or something not work ?

Matt

**Comment by jdent02** [comment]
Unfortunately due to an issue with Blender itself you cannot denoise AOVs using internal rendering. You need to use the external render options. When you activate denoising the sampling method is automatically changed to ‘importance’ so you don’t need to worry about that.

**Comment by MattRM2** [comment]
Hi, oki, tried but add this error : 
You cannot use --filtervariance without at least one lighting file.

My setup include the filtershadow to have the holdout working (Pixar Challenge) but without, still this error. Here the setup : 

[https://matthieubarbie.files.wordpress.com/2017/11/capture_aovs.png](url)
[https://matthieubarbie.files.wordpress.com/2017/11/capture_shd.png](url)

The file generated during batch rendering is this files : 

[https://matthieubarbie.files.wordpress.com/2017/11/files.png](url)

Hope you have a solution / workaround ;)

Thx,

Matt

**Comment by jdent02** [comment]
All those links 404’ed on me. You have to output AOV’s that can be denoised.  In the layers tab you should select ‘use Renderman AOVs’ (or similar. Can’t remember exactly what it’s called). Then add the AOV to denoise, and be sure to select ‘denoise AOV’ in the layer option (in addition to the render setting)

**Comment by MattRM2** [comment]
Hi Jdent02,

Yes, forgot to activated denoise aov in layers tabs... done my dumb... to much denoise to activate ;)
But, not working... denoise run but no denoise at all.

For this time, I'll use neat image
Thx,

Matt
