### ISSUE TITLE
Can't make file paths for textures absolute.

### ISSUE THREAD

**Issue by q6** [prman-pixar/RenderManForBlender#557]
`File > External Data > Make all paths absolute `

Does nothing.

**Comment by jdent02** [comment]
Nor will it ever.  None of the texture names on Pixar materials are stored in Blenders internal texture system so it has no idea that they are even there.  This is just a limitation of the exporter design.

Sent from my iPhone

On Nov 19, 2017, at 8:19 PM, 5N01F <notifications@github.com<mailto:notifications@github.com>> wrote:


File > External Data > Make all paths absolute

Does nothing.

**Comment by q6** [comment]
Couldn't the plugin devs add this functionality?

**Comment by jdent02** [comment]
Yes, but that would require a major redesign of the texture functions.  It's not a small task.

**Comment by fxzt** [comment]
那真是艰辛的工作，辛苦了！

2017-11-22 22:26 GMT+08:00 Jon D <notifications@github.com>:
