### ISSUE TITLE
21.7 throws exeption during startup

### ISSUE THREAD

**Issue by adminradio** [prman-pixar/RenderManForBlender#569]
If 21.7 is installed and the preferences (or RMANTREE) are pointing to it, the addon throws a TypeError complaining a BoolProperty() is too long with a size longer than 63.

The property is: `'Texture.Filtering And Defaults.Advanced Texture Settings_ui_open'`

Since `_ui_open` is added automatically, replacing `_ui-open` with something shorter like `_uio` over the entire code base hase solved this for me.

**Comment by RicardasSim** [comment]
same here, linux, blender-2.79a
TypeError: BoolProperty(): 'Texture.Filtering And Defaults.Advanced Texture Settings_ui_open' too long, max length is 63
ValueError: bpy_struct "PxrLayeredTexturePatternNode" registration error: Texture.Filtering And Defaults.Advanced Texture Settings_ui_open could not register

also changed _ui_open to _uio, solved problem for me to

Thanks adminradio

**Comment by sollozzo13** [comment]
How can I fix this problem? I can't find 'Texture.Filtering And Defaults.Advanced Texture Settings_ui_open' bool property.

Linux 64-bit Blender 2.79a

**Comment by RicardasSim** [comment]
as suggested by adminradio, replace every "_ui_open" to something shorter, for example "_uio"  over the entire code base

actualy replaced every "_ui_open" to "_ui_o" in:

shader_parameters.py
nodes.py
ui.py

works to, does not exceed lenght

**Comment by adminradio** [comment]
@sollozzo13 the property is autogenerated during startup and can't be found directly in the code. A quick (and some kind dirty) solution is to shorten the postfix `_ui_open` to `_uio` or similar. This works, because the property exceeds the max length only by two chars.

I'll search for a better solution in the next few days.

**Comment by alexsadovskiy** [comment]
Hi guys!
How can I fix this problem?
![image](https://user-images.githubusercontent.com/37478341/37556752-5199ab22-2a0b-11e8-8fee-af2061d1d1aa.png)

Windows 10 64-bit Blender 2.79a

**Comment by jdent02** [comment]
Do you save your user preferences with the addon enabled?  If so it automatically tries to load it at startup. If it makes it halfway through registration and fails, then trying to enable it again can cause that error

**Comment by Harvester62** [comment]
RicardasSim, thank you for your solution, it fixed the error and now the official PRman add-on for Blender is working. 

Windows 10 Pro 64bit (1511) + Blender 2.79b 64bit (portable) + RenderMan 21.7 + RMfB 21.5
