### ISSUE TITLE
Error when trying to enable the add-on

### ISSUE THREAD

**Issue by Santel22** [prman-pixar/RenderManForBlender#570]
![image](https://user-images.githubusercontent.com/37513945/37569208-8efef332-2ae7-11e8-9c97-f1075877dfea.png)
 
So, i am new here and i wanted to get renderman for blender. I am using rendeman 21.7 and blender 2.79. I don't know what to do at all. I'm 14 btw, so dont expect me to understand everything.

Please help, thanks!

**Comment by thedaemon** [comment]
http://prntscr.com/isx8mk

I am getting a similar issue on MacOS.

**Comment by obinet** [comment]
I have the same problem. Windows7, blender 2.79a, renderman for blender 21.5

**Comment by devvoid** [comment]
Same problem here. Windows 10, Blender 2.79a, Renderman for Blender 21.5. I also tried out 21.4 and it had the same issue.

**Comment by adminradio** [comment]
For RenderMan 21.7 you need to install from current master:

**Comment by obinet** [comment]
Thank you very much. This works :)

**Comment by stgfx7** [comment]
Well, I got PRman installed, got a Successful! install so on to Renderman for blender. Wham! same error trying to install with PRman 21.7 nogo line 350 enable error. tried link above but unable to find archieve. In Github I have tried three times with download with same as above results.Help needed! mac os 10.13.4 PRRenderman 21.7 Blender 2.79 2017 11-04 date.

**Comment by GyanAcomt** [comment]
This issue stays still for me, with RRman 21.7 and Blender 2.79.4 successfully installed. The only version of the zip file I've downloaded is the latest release. And I have also tried to remove the installation of PRman and reinstall for several times.

**Comment by adminradio** [comment]
For RenderMan 21.7 you need to install from current master (NOT release):
https://github.com/prman-pixar/RenderManForBlender/archive/master.zip

**Comment by GyanAcomt** [comment]
Not work, either on my mac or windows device T.T
