### ISSUE TITLE
renderman 21.7  for blender

### ISSUE THREAD

**Issue by vikipretium** [prman-pixar/RenderManForBlender#575]
![image](https://user-images.githubusercontent.com/20333314/40344055-9e2b38ba-5db0-11e8-957e-bd3c1d06b98d.png)
I got this error after i updated to renderman 21.7

**Comment by RicardasSim** [comment]
issue #569

Use latest git
Disable addon and save user preferences
exit Blender
start Blender again
Try to enable addon and if it works, save user preferences

**Comment by vikipretium** [comment]
thanks @RicardasSim. Its working perfectly...
