### ISSUE TITLE
Blender 2.79b RMANTREE not valid

### ISSUE THREAD

**Issue by userx-bw** [prman-pixar/RenderManForBlender#577]
renderman

RenderMan-InstallerNCR-21.7.0_1837774-linuxRHEL6_gcc44icc150.x86_64
![blenderrendermanerror](https://user-images.githubusercontent.com/6270942/42293204-1d94b66c-7f9e-11e8-8a80-2d48f0e595cc.png)

**Comment by jdent02** [comment]
Is Renderman in your /opt directory?  If not the addon may not be able to find it.

Sent from my iPhone

On Jul 4, 2018, at 3:24 PM, Mike <notifications@github.com<mailto:notifications@github.com>> wrote:


renderman

RenderMan-InstallerNCR-21.7.0_1837774-linuxRHEL6_gcc44icc150.x86_64
[blenderrendermanerror]<https://user-images.githubusercontent.com/6270942/42293204-1d94b66c-7f9e-11e8-8a80-2d48f0e595cc.png>

**Comment by userx-bw** [comment]
I had to / well what I did was convert the rpm to a tgz to install RenderMan on Slackware. Now I removed that install, untared the rpm and moved it into 
```
$ ls /opt/pixar/RenderMan-Installer-ncr-21.7
bin  lib
```
then I tried installing the addon again and got the same error.

**Comment by userx-bw** [comment]
I'm in the process of trying to figure this all out, messing with your code a bit . changing the version number for blender and RenderMan then I ventured into  /opt/pixar/RenderMan/bin and found an installer and ran that and it is now asking for an ID and pass word but its the free one, so I am checking my email to see what I told them for my user name and password as It error'ed out on the first try.

**Comment by jdent02** [comment]
Because most content producers use Red Hat Linux or something similar that uses RPM files

**Comment by userx-bw** [comment]
I was on my way to email them (Pixar) and "yell" at them. in form them. is the only way to actually install renderMan is to run that installer in bin? if I can get a older ver firefox that it said it was looking for maybe that is why it cannot log into the server on that side to query my USER ID

**Comment by RicardasSim** [comment]
you can't install becouse of incompatible libssl, workaround is here:
https://blenderartists.org/t/pixar-renderman-for-blender/646404/611

**Comment by userx-bw** [comment]
sudo ln -s /usr/lib/libssl.so.1.0.0 /opt/RenderMan-21.7-installer/lib/3rdparty/Qt-5.6.1/lib/libssl.so
Because this (Slackware and (archLinux) Manjaro, currently on Manjaro doing this) is not an rpm Linux system, I got an RenderMan Not installed error, not rpm system / or not Linux, and proceed option. -> clicked proceed, -> maya not installed, look anyways, selected look anyways. all it showed was the server, clicked to show all, it did, selected server and examples. 

done, it opened a web page to https://renderman.pixar.com/installSuccess
failed for addon still getting the same error, I got the /opt/pixar/pixar.license
/opt/RenderMan-21.7-installer is still the only other one pertaining to this RenderMan. Does it have to be a specif directory name in opt and or what are the exact  hot wire instructions from the start for non rpm Linux OS'es?
what I did.

Untar the rpm moved into /opt. Leaving me with /opt/RenderMan-21.7-installer ; not actually installed via rpm, preformed fix per RicardasSim fix link, (thank you), got errors already stated, as well as the rest has already been written in this post. 

(This is documentation if anything, now I got a get a coffee and put my glasses back on, time to play and see if I can hopefully figure this out)

**Comment by userx-bw** [comment]
For clarity in how to install this via Not an rpm.
1. untar RenderMan-InstallerNCR-21.7.0_1837774-linuxRHEL6_gcc44icc150.x86_64.rpm
2. go into the untared /opt directory structure, sudo mv pixar/RenderMan-Installer-ncr-21.7 /opt
3. fix sll lib link if necessary. find your version libssl.so link per post by RicardasSim above.
4. login, if error, select to keep going until you get the option to downlond the server end. do so, and anything else you may want.
5. untar RenderManProServer-21.7_1837774-linuxRHEL6_gcc44icc150.x86_64.rpm
6. do the same as you did for the installer. mv or cp -r pixar /opt
7. open blender then install addon
8. done 
thanks for the help!
