### ISSUE TITLE
renderman 22 for blender  

### ISSUE THREAD

**Issue by alexchenfeng** [prman-pixar/RenderManForBlender#580]
Have any one using renderman 22 with blender?

**Comment by vikipretium** [comment]
![image](https://user-images.githubusercontent.com/20333314/45447825-68b58b80-b6ee-11e8-9017-24845723742f.png)
renderman exited !

**Comment by bl4ck1c3** [comment]
Anyne know if it will support Rendermann 22?

**Comment by alissone** [comment]
I'm waiting for it too, as I can't download any previous version from the official site. What exactly do we still need to port it to PRMan 22?

**Comment by ma0mpt** [comment]
Same issue.  The current version of the plugin does not work with Renderman 22.

**Comment by mj-saunders** [comment]
I managed to install it, after some effort (on Arch linux).
Thought I couldn't get it to render, but I just checked again and it works. Sort of.
I have some licensing bugs, because I also have ProServer21.5 installed and they seem to clash a little as it looks like 'it' sometimes expects only one license file 'pixar.license'.
Single frame render appears to work, IPR does not.

Is there anyone who can advise where to begin with debugging?

**Comment by ma0mpt** [comment]
The RfB plugin *WILL* detect the presence of NCR 22. And it didn't matter for me how I tried to configure the RMANTREE env variable with the plugin preferences - it always resulted in a Blender crash when trying to render a scene. Solution: de-install NCR 22 or move it where the RfB plugin cannot see it. This action appeared also to solve the problems I had trying to install previous versions of the RfB plugin.

Back in action with Blender 2.79 / RfB plugin / NCR 21.4 :-) !!!

**Comment by ma0mpt** [comment]
Fact: Pixar has not publicly released the new API for NCR 22.  
Corollary: Therefore the existing (21.5) RFB plugin cannot be compatible with NCR 22.
Assumption: I believe that is the reason why the RfB plugin causes Blender to crash if you install NCR 22 and then try to use the plugin.  It (the plugin) will be sending 'old' API calls to NRC 22 - resulting in all kinds of nastiness.  I could be wrong though - just my guess.  Even when I tried to configure various versions of RfB to use older NCR versions they either refused to install or (latest master version of RfB) if it *did* install it caused Blender to crash.  These problems went away when I removed NCR 22 from my machine.

**Comment by mj-saunders** [comment]
Cool you got functionality with NCR 21.4

> Fact: Pixar has not publicly released the new API for NCR 22.
> Corollary: Therefore the existing (21.5) RFB plugin cannot be compatible with NCR 22.
> Assumption: I believe that is the reason why the RfB plugin causes Blender to crash if you install NCR 22 and then try to use the plugin. It (the plugin) will be sending 'old' API calls to NRC 22 - resulting in all kinds of nastiness. I could be wrong though - just my guess. Even when I tried to configure various versions of RfB to use older NCR versions they either refused to install or (latest master version of RfB) if it _did_ install it caused Blender to crash. These problems went away when I removed NCR 22 from my machine.

I would definitely agree. I've seen some commandline error messages that mention functions (like WorldBegin()) no longer being accepted.

**Comment by WireFX** [comment]
Is there any location to download NCR 21.5? I only got 22 here and for me also I have permanent crashes.

**Comment by WireFX** [comment]
I am unsing Win 8.1 as OS

**Comment by mj-saunders** [comment]
Sorry, I have a linux installer I could have sent you, but nothing for Windows. Perhaps someone else can help, assuming this doesn't breach something I am unaware of.

**Comment by NazzarenoGiannelli** [comment]
I would love to be able to use Renderman 22 on Blender! Any clue n when it could be available an addon update for that?
Can't find any 21.5 installer for Windows to at least have Renderman working while waiting for the update

**Comment by arabadzhiyski** [comment]
I have the win 21.7 which i'm still using with blender 2.79b here: https://1drv.ms/f/s!AjmekNQU6mFNiNQiM3jeSff1JPkxdQ

**Comment by schroef** [comment]
@arabadzhiyski, thanks foe the link. I'm on OSX so i cant use your link. Thanks for the help.

**Comment by NazzarenoGiannelli** [comment]
> I have the win 21.7 which i'm still using with blender 2.79b here: https://1drv.ms/f/s!AjmekNQU6mFNiNQiM3jeSff1JPkxdQ

Thanks for the link!
Unfortunately it looks like I can't get a NCR license for 21.7. It keeps me push to download the 22 one. So I have your 21.7 correctly installed, but it's not activated with a valid license :(

**Comment by thebarz** [comment]
> Sorry, I have a linux installer I could have sent you, but nothing for Windows. Perhaps someone else can help, assuming this doesn't breach something I am unaware of.

I would be glad if you can share with me the version you have for Linux. I am done with Xgen on Maya, I prefer using particles for Hair on Blender. The version 22 is something I can't use with blender as well.

**Comment by schroef** [comment]
I wonder if prior versions can even be installed properly. Reading the prior post, it keeps pushing to update to 22 when trying to license it.

**Comment by thebarz** [comment]
In linux might be different. I want to try it anyway

**Comment by mj-saunders** [comment]
> In linux might be different. I want to try it anyway

I'll see what I can do. Internet connection has been capped for the moment, so I may have to wait a few days.

**Comment by mj-saunders** [comment]
@thebarz check here: https://filebin.net/19qk008mikxkrxey

I guess, try the installer first... Else, I think manually installing and running the license app directly may work.

**Comment by mj-saunders** [comment]
> Thousands and millions of thanks! As I saw this on my e-mail, I jumped in joy from my bed to the computer, just to download it. Really, thanks a lot!

Haha, you're welcome. Good luck, hope you can get it to work.

**Comment by PeterGutsche** [comment]
https://codeload.github.com/prman-pixar/RenderManForBlender/zip/master

I was able to import this RenderMan-Plugin into Blender (2.79, Ubuntu 18.04) with a RenderMan 22 installation.
I don't know yet if it is working, I can find all kinds of RenderMan options in Blender now, but as a noob I'm still struggling to see something rendered by it. :)

**Comment by schroef** [comment]
@PeterGutsche ,

what do you see in the console? Because 22 wil not work with Blender. Nothing happens, you see tons of errors in the console

**Comment by RaneMstSage** [comment]
> https://codeload.github.com/prman-pixar/RenderManForBlender/zip/master
> 
> I was able to import this RenderMan-Plugin into Blender (2.79, Ubuntu 18.04) with a RenderMan 22 installation.
> I don't know yet if it is working, I can find all kinds of RenderMan options in Blender now, but as a noob I'm still struggling to see something rendered by it. :)

That worked though RenderMan IT closes now...

**Comment by mj-saunders** [comment]
@PeterGutsche @RaneMstSage I'd managed to get a normal render out of NCS 22, but IPR definitely doesn't work.
Looks like the API might be out early 2019 (hopefully the first month or two). I think we shall have to wait until then before we can get a stable update to RfB

**Comment by mj-saunders** [comment]
@schroef I could be wrong but I'm fairly certain at some point I got a straight render to 'it' working.
IPR is the big fail for the time being.
But having said that, I just tried to get it going again, and now all I get is a crash.

This post here also suggests that the main break is with IPR until the relevant new API is released.
(https://renderman.pixar.com/forum/showthread.php?s=&postid=231672#post231672)

**Comment by schroef** [comment]
I havent used this before, so probably im wrong.  I just stated what i read and what people of renderman said.

**Comment by SamMcfly** [comment]
Maybe they are waiting the final release of Blender 2.8 to release an update of the plugin.

**Comment by fxzt** [comment]
只能期待

**Comment by schroef** [comment]
嗯，不是每個人都讀中文
