### ISSUE TITLE
Blender 2.79b crashes when used with Renderman 22.1 for rendering a simple scene 

### ISSUE THREAD

**Issue by ganeshbelgur** [prman-pixar/RenderManForBlender#584]
When I try to render (Render Image Option, F12) the default Blender (2.79b) scene with the cube in it using Renderman (22.1) as the rendering engine, it crashes with the following message:

Console:
~~~
Read prefs: /home/ganesh-pc/.config/blender/2.79/config/userpref.blend
found bundled python: /home/ganesh-pc/Documents/developments/blender-2.79b-linux-glibc219-x86_64/2.79/python
Writing: /tmp/blender.crash.txt
Segmentation fault (core dumped)
~~~

Stack Trace:
~~~
# Blender 2.79 (sub 0), Commit date: 2018-03-22 14:10, Hash f4dc9f9d68b
bpy.context.scene.render.engine = 'CYCLES'  # Property
bpy.context.scene.render.engine = 'PRMAN_RENDER'  # Property

# backtrace
./blender(BLI_system_backtrace+0x20) [0x1a6c700]
./blender() [0x1078395]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7fd94417c4b0]
/opt/pixar/RenderManProServer-22.1/bin/prman_for_python_35.so(+0x13858) [0x7fd91d382858]
/opt/pixar/RenderManProServer-22.1/bin/prman_for_python_35.so(+0x10b59) [0x7fd91d37fb59]
./blender(PyCFunction_Call+0xb9) [0x2e9d579]
./blender(PyEval_EvalFrameEx+0x81ec) [0x2f16d7c]
./blender() [0x2f1869e]
./blender(PyEval_EvalFrameEx+0x6c8a) [0x2f1581a]
./blender(PyEval_EvalFrameEx+0x74eb) [0x2f1607b]
./blender() [0x2f1869e]
./blender(PyEval_EvalCodeEx+0x23) [0x2f18773]
./blender() [0x2e79674]
./blender(PyObject_Call+0x5c) [0x2e4f06c]
./blender() [0x1472964]
./blender() [0x19a7cd7]
./blender(RE_engine_render+0x312) [0x13f1c92]
./blender() [0x14046e9]
./blender() [0x1404d18]
./blender() [0x140814a]
./blender(RE_BlenderFrame+0xbe) [0x140879e]
./blender() [0x134a121]
./blender() [0x10887ba]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fd945a306ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fd94424e41d]
~~~

I'm using the master branch of RenderManForBlender and not the latest release 21.5.
Is the add-on ready for Renderman 22.1 with Blender 2.79b?
Please help!

**Comment by alissone** [comment]
I'm facing the exact same issue, even the stacktrace is identical. I hope there is someone working on this...

**Comment by mj-saunders** [comment]
Do you have Python3.5 installed?
I'm running 3.7 and had to make some tweaks to get things partially working

**Comment by schroef** [comment]
> Do you have Python3.5 installed?
> I'm running 3.7 and had to make some tweaks to get things partially working
I got an error on osx 10.1.6 stating something about missing Python lib 3.5. So i checked the frameworks folder and saw only 3.4 and 3.6 than i added 3.5.4 and now bl instantly crashes. 

This was the error i got before installing Python 3.5.4
```
Traceback (most recent call last):
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/__init__.py", line 64, in update
    engine.create(self, data, scene)
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 104, in create
    engine.render_pass = RPass(scene, preview_render=engine.is_preview)
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 204, in __init__
    init_prman()
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.78/scripts/addons/RenderManForBlender/engine.py", line 79, in init_prman
    import prman
  File "/Applications/Pixar/RenderManProServer-22.2/bin/prman.py", line 80, in <module>
    import prman_for_python_35 as prman_for_python
ImportError: dlopen(/Applications/Pixar/RenderManProServer-22.2/bin/prman_for_python_35.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.5/Python
  Referenced from: /Applications/Pixar/RenderManProServer-22.2/bin/prman_for_python_35.so
  Reason: image not found
```

**Comment by mrcivvy** [comment]
Hey guys,

I had a chance to speak to one of the developers from Pixar at the recently concluded Siggraph Asia conference. Apparently, RendermanForBlender will be updated around the time of release of Renderman 23.0 some time in 2019. The developer said Pixar plans to continue support for RendermanForBlender and it is definitely on their radar.

Hope that helps!

-Ganesh

**Comment by schroef** [comment]
I also had a chat and they said they are working on updates. But they could not tell when it would be ready. I though that someone outside Pixar was working this though. The issue is that they have not made API open

**Comment by ganeshbelgur** [comment]
Hey guys,

Pixar made announcements about the new Renderman release recently.
They will be actively supporting Blender going forward, starting with the release of Renderman 24.

With this development, it no longer makes sense to keep this issue open.
I'll be closing it.

Thanks,
Ganesh
