### ISSUE TITLE
Renderman not showing up, plugin displaying an error

### ISSUE THREAD

**Issue by julioplayz** [prman-pixar/RenderManForBlender#588]
I just installed the plugin, and it shows i need to update to 2.8x, issue is i'm running Blender 2.81

Not only that, there isn't an option to switch to RenderMan in the rendering engines

here's a screenshot
![Blender Preferences 12_4_2019 7_56_19 PM](https://user-images.githubusercontent.com/14865387/70194372-2e0f8880-16d0-11ea-8e5a-b04d563e37c1.png)

**Comment by foreachthing** [comment]
The plugin needs to be updated to 2.8x ... _you_ are already using Blender 2.8x.
Same "issue" here ... not going back to 2.79. So, I can't use RenderMan until the plugin gets updated.

**Comment by jasonvfx** [comment]
Sadly I don't think this is supported anymore. Prman is on 23 and I see no sign of this plugin being updated. Blender has been on the 2.8x branch for a while already. It's really sad because I think there is a big movement to use this, and Renderman is wonderful. I really wish someone would pick it up and maintain the plugin. The last time files were released was 17 months ago... sad times.

**Comment by mistrrhappy** [comment]
It looks pretty bleak- Brian was the main dev, and once he left, it fell by
the wayside. Pixar is a big outfit, but they don’t have spare bodies to
throw at these projects, either.

**Comment by Seefer** [comment]
I'm a Blender noob and have started with 2.90.1. Isn't blender used commercially too and do addons for other software such as the Autodesk lineup have the same issue with plugin support as we are seeing here? Or is it just a lack of interest in supporting Blender? I get the impression third-party renderer addons for Blender is generally not a market. On Youtube I see coverage of V-Ray for Blender etc but it all seems so out of date and no longer applicable to newer Blender versions. Very confusing for newcomers.

**Comment by pleprince** [comment]
If we had customers using Blender, we would allocate more resources to Blender. Sadly, I don't think we have a single one.
A new RenderMan plugin is coming. The plugin's code will be open-sourced and anyone will be able to help support it.

**Comment by PYLOTT** [comment]
I'm a customer using Blender! :'(

talking a bit about the new plugin, will it be available on GitHub, or will it be on a custom git service such as GitLab? also, will it comes soon?

thanks for your time though.
