### ISSUE TITLE
RendermanForBlender Renderman 24 version makes Blender preferences window incredibly laggy

### ISSUE THREAD

**Issue by 3Rton** [prman-pixar/RenderManForBlender#595]
Pretty self-explanatory 

RendermanForBlender Renderman 24 version makes Blender preferences window incredibly laggy when the "Renderman For Blender" add-on preferences are rolled out. Interestingly the preferences window goes back to being snappy the moment you un-roll the preferences.

**Comment by prman-pixar** [comment]
Just committed a fix for this.
