### ISSUE TITLE
Blender Icons all turn black when using Renderman

### ISSUE THREAD

**Issue by Christopher-Hosken** [prman-pixar/RenderManForBlender#596]
Like said in the title, All the UI icons in blender go black when using renderman. 
![image](https://user-images.githubusercontent.com/67215158/123898689-f5a95c80-d98f-11eb-9273-b411b4e5dbd9.png)

**Comment by prman-pixar** [comment]
This seem to be a known issue with 2.92. It doesn't seem to happen in 2.83. I've talked to another Blender render addon developer and they said they were seeing the same thing, so it's not unique to us.

**Comment by prman-pixar** [comment]
Just as an addition, rendering to "it" instead shouldn't have this problem either, I believe.
