### ISSUE TITLE
Cancelling a render rendering to "it" closes blender

### ISSUE THREAD

**Issue by sharaths21312** [prman-pixar/RenderManForBlender#598]
When rendeman is set to render to it, and when cancelling the render in it (By either pressing esc or pressing the button), it crashes blender. This applies for ipr and final renders. However, cancelling the render from the blender window doesn't cause this.
[blender_debug_output.txt](https://github.com/prman-pixar/RenderManForBlender/files/6739372/blender_debug_output.txt)
> R56005 {SEVERE}  Renderer completing shutdown request. (System Error: Invalid argument)
> Error: Not freed memory blocks: 167255, total unfreed memory 65.522133 MB

**Comment by prman-pixar** [comment]
This is a known issue and it's mentioned in the docs.

https://rmanwiki.pixar.com/display/RFB24/RenderMan+for+Blender+24.0

You'll need to cancel the render in Blender.

**Comment by sharaths21312** [comment]
The docs seem to not load for me, is the website down or something?
