### ISSUE TITLE
unable to activate addon

### ISSUE THREAD

**Issue by jishnuthewalker** [prman-pixar/RenderManForBlender#599]
when i try to activate it it shows the following

![blender_kDNSgi2UA5](https://user-images.githubusercontent.com/26621554/124093689-b6553b80-da75-11eb-93df-272a93397c19.png)

edit1; I tried reinstalling both blender and Renderman multiple times. added rmantree to the bin and restarted my pc. nothing seems to solve the problem.

Windows 10 (19042.1052)
Blender 2.93.1
Renderman 24 (latest)

**Comment by riedmu** [comment]
> 
> 
> when i try to activate it it shows the following
> 
> ![blender_kDNSgi2UA5](https://user-images.githubusercontent.com/26621554/124093689-b6553b80-da75-11eb-93df-272a93397c19.png)

Same problem here.

Windows 10 (19043.1052)
Blender 2.93.1
Renderman 24 (latest)

**Comment by askmetoo123** [comment]
Atm you need Blender 2.83 LTS or Blender 2.92 to make ADD-on work :) I got same errors with 2.93.1. Hope that they will upgrade it for 2.93.x soon :)

**Comment by wallmanfx** [comment]
> Atm you need Blender 2.83 LTS or Blender 2.92 to make ADD-on work :) I got same errors with 2.93.1. Hope that they will upgrade it for 2.93.x soon :)

Thanks!! I will try it again with 2.92

**Comment by sn1pah** [comment]
when i try to activate it it shows the following
![obrazek](https://user-images.githubusercontent.com/20222867/124379198-d8d59780-dcb5-11eb-9f5a-29fee58d2b7a.png)
Windows 10 (19042.1052)
Blender 2.83 LTS
Renderman 24 (latest)

**Comment by prman-pixar** [comment]
@sn1pah  Have you installed RenderMan Pro Server as well? That is needed for RenderMan for Blender to work.

**Comment by f1vefour** [comment]
I imagine it will be updated to support 2.93.0 LTS but it's unlikely Pixar is going to support later builds any time soon.

**Comment by sn1pah** [comment]
> 
> 
> @sn1pah Have you installed RenderMan Pro Server as well? That is needed for RenderMan for Blender to work.

![obrazek](https://user-images.githubusercontent.com/20222867/124712462-a0c19500-deff-11eb-8a7c-63436d1976b5.png)
yes i do. It is my screenshot from installation.

**Comment by prman-pixar** [comment]
@f1vefour  2.93 LTS support will come when RenderMan 24.1 ships.

**Comment by f1vefour** [comment]
@prman-pixar Sounds good, thank you for the update.

**Comment by axalox** [comment]
Hello

When will it be available, you have an idea ?

**Comment by prman-pixar** [comment]
@axalox  24.1 is out now, if you want to test 2.93.

**Comment by axalox** [comment]
Ok thx :)
