### ISSUE TITLE
Linux problem

### ISSUE THREAD

**Issue by schulze1963** [prman-pixar/RenderManForBlender#602]
On windows all works ok. On Linux (Ubuntu 21.04) I managed to install renderman installer and unpack the rendermanproserver in opt / pixar. The plugin can be easily installed and activated in Blender 2.92. But I get the error message "error in RMANTREE ....." 
 
![Bildschirmfoto von 2021-07-04 15-02-25](https://user-images.githubusercontent.com/86917620/124386389-7fcc2a80-dcda-11eb-9f28-40dfba327329.png)

**Comment by wesol4** [comment]
try to install  

`sudo apt install libncurses5`

**Comment by schulze1963** [comment]
great, that helped. Many Thanks
