### ISSUE TITLE
Blender crash if trying to open a while while IPR

### ISSUE THREAD

**Issue by riouxr** [prman-pixar/RenderManForBlender#605]
If you are rendering in IPR and try to open another file Blender will crash

**Comment by prman-pixar** [comment]
OK, I can reproduce this 2.83.16 and 2.92, but with our dev build running 2.93, I'm not getting a crash, so seems like this was a problem on the Blender side.

I'll keep this issue open, but please let us know if you still get this when RenderMan 24.1 ships using Blender 2.93.
