### ISSUE TITLE
Renderman makes the scene heavier on the viewport.

### ISSUE THREAD

**Issue by nuzzar** [prman-pixar/RenderManForBlender#612]
It seems that when you set the renderer to renderman the scene become a lot heavier that makes it hard to navigate around in the viewport.

Way to reproduce:
- Open The Hidden People example scene.
- Try to navigate on the viewport with the viewport shading in solid mode.
- Change the renderer to eevee or cycles.
- Try to navigate again. You can notice the difference. It looks like the scene become a lot lighter and easier to navigate.

**Comment by prman-pixar** [comment]
Can you try turning off the light wireframe and light texturing and see if it's faster? You can turn those off in the RfB preferences.

**Comment by nuzzar** [comment]
Hi, it works. It became a lot lighter. Thanks. I also noticed similar problem when rendering to It (both render and ipr). This fix doesn't work for that though. But I think I'm gonna make a new thread for that.

**Comment by nuzzar** [comment]
I think this is a bug. I tested it with blender default cube scene with a pixar atrium. When I turn on all the setting where the light wireframe settings is. It became quite hard to navigate in Blender 2.93. However this is not the case in Blender 2.92.

**Comment by prman-pixar** [comment]
OK, thanks for confirming. The slowness is probably because we are looping through all of the objects, trying to get a list of the lights in the scene. I'll look into ways to speed that up.

**Comment by prman-pixar** [comment]
Can you see if the latest commits make it feel better for you?

**Comment by nuzzar** [comment]
I tested it with the one on the main branch. I think it's more or less the same. It could be a little bit better, but it's hard to say. The one on Blender 2.92 feels like there's not much impact at all.

**Comment by nuzzar** [comment]
You can see the difference in this video. [https://youtu.be/F2_fnpuMaY0](https://youtu.be/F2_fnpuMaY0)

**Comment by prman-pixar** [comment]
I'm not seeing any slow down like what you're demonstrating in your video with 2.93, on my Windows machine. Do you have another machine that you can test with, that also shows the same issue? I can sort of get it to slow down if I have two copies of Blender running, but I would think that's expected. Is that what you're doing?

**Comment by nuzzar** [comment]
Nope, I only did that so I don't have to edit the capture. It's same with one instance of blender. I see. That's weird. Unfortunately, I don't have other machine at the moment. 

For the record, I'm on a laptop with 16 gb and RTX 3060, on Windows 10.

By the way when I render IPR to It, I also feel the same thing happening. Do you also not experiencing this?

**Comment by nuzzar** [comment]
@prman-pixar The problem vanished when I copy the patch again. It seems like I made some mistake when copying them before. Thanks for the help and sorry for taking your time.

Btw, the problem when rendering IPR to It still happens though. Do you also experiencing this?

**Comment by prman-pixar** [comment]
Which problem with IPR are you referring to? That it's slow to tumble the camera when IPR is started? If so, how much of a slow down are we talking about? Some slow down is expected, but it's not clear how much you're seeing.

**Comment by nuzzar** [comment]
It's pretty bad actually. You can see it in the video along with some of the bugs that I found.

- Tumbling the camera during IPR in It is really slow (1st launch)
- Blender will crash when you hover over the overlay menu on the viewport during IPR (both blender and It) (1st launch)
- Importing the environment and the lighting from the preset browser will produce some error. Importing material work as expected. (2nd launch). Importing from the menu work as expected as you can see in the 1st launch.
- When you render to It, you can see some activity on the blender image viewer. Because of this when you set your temporary editors to new window and you render to It, blender will launch its own image viewer. This is a nuisance. If this is due to blender limitation, wouldn't it be a great idea to expose those settings on the property window to make it easier to change it? (3rd launch)

Here's the video link, https://youtu.be/aerJAaEUgS8

**Comment by TzurH** [comment]
Just want to add to this, I'm also experiencing bad viewport performance when IPR to IT is executed as shown in the video above.
I'm running on Blender 2.93.2 with the latest patch available on GitHub and my machine specs are RTX 2070 Super and Ryzen 9 3950x and even when I set the Render Threads for RenderMan to only use 3 threads (out of my 32 available threads), the viewport performance seems to be the same.
IPR in Blender is very responsive.

**Comment by nuzzar** [comment]
@TzurH What about my second and third bugs on the list? Do you also experience these issues?

**Comment by nuzzar** [comment]
I use the addon from the main branch from 6 days ago. I don't think the debug logging is the issue. I only set the logging to debug for the video so you can see them.

Here's the result with the latest main.

- tumbling speed: The tumbling speed on the viewport (not camera) has significantly improved however the tumbling speed with the camera for ipr only improved a little bit. It's still really slow. Turning off lights texturing helps a little bit, but it's still really slow.

- importing from preset browser will produce error: Now it works as expected.

- hovering the overlay menu: It no longer crashes when hovering the menu.

- When you render to It, you can see some activity on the blender image viewer: I wish there's a way to change that settings temporarily so we can change it automatically and doesn't mess with user's preferences.

**Comment by prman-pixar** [comment]
Can you see if my latest commit fixes the tumbling problem?

https://github.com/prman-pixar/RenderManForBlender/commit/f04f6882e01ec8a379a8440353625b0c3e570d84

**Comment by nuzzar** [comment]
Good news. It fixed the bug. Great work and thanks.

**Comment by TzurH** [comment]
I can also report that using this code from 17/08 ([https://github.com/prman-pixar/RenderManForBlender/tree/2e8c0214a88b5d81ca6b9d7af0e83af5e629ec95](url)) fixed the performance issue I was experiencing in Blender viewport when rendering to IT.
As for the other issues reported here by @nuzzar regarding preset browser error and hovering over viewport overlay crashing Blender - I'm not experiencing those either.

Good stuff!

**Comment by prman-pixar** [comment]
Great! Thank you both for confirming.
