### ISSUE TITLE
[2.93.2] Enable light temp crashes Blender

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#614]

**Comment by TzurH** [comment]
Hi, running on Blender 2.93.2 with the latest Renderman and patch available here on GitHub.
If light temperature checkbox is checked, Blender will crash.

**Comment by prman-pixar** [comment]
I can't reproduce what you're seeing with enable temperature. Can you give me some steps or what the circumstances were when it crashed?

**Comment by TzurH** [comment]
Seems to have been caused by an AddOn I had enabled. I can't reproduce this crash after disabling it. Can close, thanks.

The AddOn is called Extra Lights for anyone who might have the same issue.
