### ISSUE TITLE
[2.93.2] IT crashes Blender when 'Cancel Render' button is executed and render isn't finished

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#615]
Running on Blender 2.93.2 with the latest Renderman and patch available on GitHub.

If you press 'Cancel Render' in IT and the render isn't complete (not reaching max stated samples?), Blender will crash.

Doesn't crash Blender if the render has finished. Can stop render within Blender using the 'Stop IPR' button (Blender isn't very responsive when rendering to IT though).

Not sure if matters, my sys specs:
Geforce RTX 2070 Super
Ryzen 9 3950X

**Comment by prman-pixar** [comment]
This is a known issue. It requires some changes to the core of renderer to support canceling from "it".
