### ISSUE TITLE
[2.93.2] Using PxrBlackBody to pass colour causes a crash

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#616]
Running on Blender 2.93.2 with the latest Renderman and patch available on GitHub.

So far, I have tried using PxrBlackBody to pass resultRGB from the node into Diffuse colour, and Glass Refraction Colour of PxrSurface, both producing a crash.

Possibly a bug with the PxrBlackBody node?

My specs:
RTX 2070 Super
Ryzen 9 3950x

**Comment by prman-pixar** [comment]
Hmm...I'm not seeing a crash with PxrBlackBody. Can you attach a blend file that reproduces the crash?

**Comment by TzurH** [comment]
Seems to have been caused by an AddOn I had enabled. I can't reproduce this crash after disabling it. Can close, thanks.

The AddOn is called Extra Lights for anyone who might have the same issue.
