### ISSUE TITLE
Unable to rename Light Mixer Groups

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#617]
Running on Blender 2.93.2 with the latest Renderman and patch available here on GitHub.

Not so much of an issue, more of a feature request. Would be great to have this functionality added so we can better manage our lights in the scene. For example:
Light mixer Group called 'corridor, one for 'kitchen' etc. if lighting a house. Right now we have to click each group to see the lights associated as they are named mixerGroup_N - not very descriptive.

**Comment by prman-pixar** [comment]
You can rename by holding Ctrl and clicking on the name.

**Comment by TzurH** [comment]
Oh great, thank you. I've tried dbl-clicking and F2 while having the group selected, but nothing happened so thought this functionality is missing. Maybe possible to change the behavior to be more like Blender native?
