### ISSUE TITLE
[2.93.2] Error when loading RIB archive

### ISSUE THREAD

**Issue by cedricp** [prman-pixar/RenderManForBlender#618]
Hi,
The delayed RIB archive doesn't work for me, tested with several versions of Blender and the plugin.
I find a way to make it work though, rman_translator.py around line 128 : 

```
            if rman_type in [
                    'DELAYED_LOAD_ARCHIVE',
                    'ALEMBIC',
                    'PROCEDURAL_RUN_PROGRAM',
                    'DYNAMIC_LOAD_DSO'
                ]:
                procprimid = hashlib.sha1(rman_sg_node.db_name.encode()).hexdigest()
                attrs.SetString('user:procprimid', procprimid)
```

**user:procprimid** seems to expect a string attribute, not a float (with RenderMan 24.1 anyway)
Best regards

**Comment by prman-pixar** [comment]
I've pushed a fix for this. Let me know if it doesn't work for you.

**Comment by cedricp** [comment]
It does work, thank you
