### ISSUE TITLE
Custom attributes from geometry nodes

### ISSUE THREAD

**Issue by cedricp** [prman-pixar/RenderManForBlender#619]
Hi,
I tweaked the code to support arbitrary color attributes from geometry node, I attached a patch and a test scene to this issue.
There's a weird thing in the mesh translator, though, the blender (python) object does not behave as expected when a geometry node is attached to it.

[patch+scene.zip](https://github.com/prman-pixar/RenderManForBlender/files/7015798/patch%2Bscene.zip)

**Comment by prman-pixar** [comment]
Thanks! I've merged in your change.
