### ISSUE TITLE
PxrPathTracer UI bug

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#622]
There seems to be a bug with PxrPathTracer integrator. Change mode from bxdf to manual, no change in the UI to control individual ray samples.
Just to clarify, the integrator actually works as intended in manual mode, it's just a UI bug where it's stuck on bxdf mode.

Here you can see the UI in Blender, still stuck on bxdf.
![PxrPathTracer_UI_bug1 (2)](https://user-images.githubusercontent.com/10125645/132333908-ae3497a5-23c0-474b-a7c4-a06ccc9cd739.png)

Rendering in IT - actually using manual as intended.
![PxrPathTracer_UI_bug1](https://user-images.githubusercontent.com/10125645/132333915-c0013227-05b8-4531-a7e7-7fc435d67920.png)

**Comment by prman-pixar** [comment]
I cannot reproduce what you're seeing. Can you elaborate on what you mean by the UI is stuck?

**Comment by TzurH** [comment]
From the docs > If "sampleMode" is set to "manual" the user is responsible for explicitly specifying the number of indirect rays to spawn per Bxdf lobe at each camera hit point via the numDiffuseSamples, numSpecularSamples, numSubsurfaceSamples, and numRefractionSamples parameters.

If you look at the first image, the mode is set to manual, yet I'm unable to access these parameters.
When rendering to IT, you can see that it's actually working "under the hood".

If you open Cookies and Milk example, you'll see the integrator is set to bxdf mode but actually showing controls for manual mode.
I think this image will make more sense:
![PxrPathTracer1](https://user-images.githubusercontent.com/10125645/132428940-e3a9fcb4-2bd7-49c8-9180-3ad43f81d82d.png)

Switching Sample Mode just doesn't seem to trigger a UI change?

**Comment by prman-pixar** [comment]
@TzurH  can you see if this latest commit fixes the problem?

**Comment by TzurH** [comment]
Can confirm works as intended now. Thanks.
