### ISSUE TITLE
Texture Manager bugs

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#625]
Not sure if this is related to RfB or not, but I use the Texture Manager via Blender so I'll just report here.

1. Hitting "Reset" brings this error:
![image](https://user-images.githubusercontent.com/10125645/132640896-bb8cb7ca-fcf0-4d4b-b10a-1291eb8bb09b.png)
2.  Hitting "Apply" brings this error:
![image](https://user-images.githubusercontent.com/10125645/132641210-8e9262fe-977d-4655-9959-5b57fa1535a8.png)
3. Manual rules don't apply? Might be related to the errors above. Might also be just a visual thing. It might be actually converting properly.
https://user-images.githubusercontent.com/10125645/132643273-b6a3d37d-47e3-49da-866f-67047b8f113a.mp4
https://user-images.githubusercontent.com/10125645/132643682-bcc36f49-adfe-44ff-8b5f-9dd8e003f666.mp4

**Comment by prman-pixar** [comment]
I've pushed a fix for 2. Unfortunately, 1. is a core issue, so you'll need to wait until at least 24.2 for a fix.

**Comment by TzurH** [comment]
Okay, no worries.
Thanks for fixing 2. Can confirm no errors now.

What about 3? Do you know if the textures get converted from and to the proper color space and it's just a visual error where the Texture Manger doesn't rename the .tex file properly on disk?

**Comment by prman-pixar** [comment]
Did 3 not get fixed by 2?

**Comment by TzurH** [comment]
I've played with it a bit today as I did some lookdev. It looks like TXmanager is converting the file from the specified color space to ACEScg properly, so that's good! It just doesn't rename the .tex file properly. It will "stick" to the input color space set by the default rules in the OCIO (?) of set texture (8bit, 16bit, float...) and just won't change.

https://user-images.githubusercontent.com/10125645/132874412-2f3a0275-7454-44e0-bad5-a9ace500a2f5.mp4

**Comment by prman-pixar** [comment]
@TzurH  can you see if the latest commits fix 1 & 3 now?

**Comment by TzurH** [comment]
@prman-pixar 
Yes, can confirm both issues are now fixed! 👍

Would it be possible to add the same functionality to changes made to PxrTexture / PxrNormalMap etc. via the Shader Graph Editor?
![image](https://user-images.githubusercontent.com/10125645/132928651-f07249f0-6aae-41f0-ba12-605fb08eb505.png)
Currently it doesn't apply the changes, only when you hit "apply" via the TXmanger it would. Unless this is by design?

**Comment by prman-pixar** [comment]
@TzurH  Try my latest push.

**Comment by TzurH** [comment]
@prman-pixar Works!
Can close the issue as far as I can tell.
Awesome work! :)
