### ISSUE TITLE
Pxr math nodes bug?

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#626]
Hi, I can't seem to blend the same parameter type using the blend \ mix nodes. this seems like a bug as that is doable in Houdini.

please see the video showcasing the issue.
https://user-images.githubusercontent.com/10125645/134471083-4697c23d-57c3-4adf-8997-d1cb444fe516.mp4

Houdini, no problem
![image](https://user-images.githubusercontent.com/10125645/134471580-7089609b-df03-4e34-8e56-ac8a72823385.png)
Blender, get an error
![image](https://user-images.githubusercontent.com/10125645/134471646-a8a4a054-f1cd-4a85-8fbe-d39335560f45.png)

**Comment by prman-pixar** [comment]
@TzurH  Technically, that's not allowed in RenderMan, as you're supposed to use either PxrToFloat or PxrToFloat3 to convert between the invalid types.

I've pushed a commit that will try to automatically create the nodes for you when you connect like that.

**Comment by TzurH** [comment]
I see..
Why is it working in Houdini though, there's something happening under the hood to make the conversion for me? This cleans up the shader network and is much faster to work with, in my opinion.

Have just tried your new commit. It inserts a pxrtofloat3 node, but is unable to connect the output to the input
https://user-images.githubusercontent.com/10125645/134602565-009d1797-79a1-434a-83dc-7c56e4c7c655.mp4

**Comment by prman-pixar** [comment]
@TzurH  can you try the latest commit? There was already code to insert the conversion during export time, but I modified the code a bit for improvement.

**Comment by TzurH** [comment]
yes, this works like it does in Houdini now. that's great. thanks for the fix 👍
