### ISSUE TITLE
Appending/Linking objects with textures causing a black render and freeze

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#630]
I think this is TxManager related. If appending/linking an object from an external .blend scene, TxManager doesn't add the textures "attached" to said object automatically, the user has to parse the scene manually, which is prone to human error.  Is it possible to run "parse scene" on import/append/linking of objects to the scene?

Here's a capture to better show what's happening. I append an object with textures in the material, and TxManager isn't finding them automatically. * Please disregard the diffuse texture in the TxManger, I have a hidden object in the scene this belongs to.

https://user-images.githubusercontent.com/10125645/136289097-17cc1cc0-b22f-401e-9d6a-472554d3d93d.mp4

And this is the log:
src\liboslexec\instance.cpp:480: RMAN_1697a56_OSL::pvt::ShaderInstance::copy_code_from_master: Assertion 'm_instops.empty() && m_instargs.empty()' failed.
src\liboslexec\instance.cpp:489: RMAN_1697a56_OSL::pvt::ShaderInstance::copy_code_from_master: Assertion 'm_instsymbols.size() == 0 && "should not have copied m_instsymbols yet"' failed.
src\liboslexec\instance.cpp:494: RMAN_1697a56_OSL::pvt::ShaderInstance::copy_code_from_master: Assertion 'm_instoverrides.size() == (size_t)std::max(0,lastparam())' failed.
src\liboslexec\instance.cpp:480: RMAN_1697a56_OSL::pvt::ShaderInstance::copy_code_from_master: Assertion 'm_instops.empty() && m_instargs.empty()' failed.
src\liboslexec\instance.cpp:489: RMAN_1697a56_OSL::pvt::ShaderInstance::copy_code_from_master: Assertion 'm_instsymbols.size() == 0 && "should not have copied m_instsymbols yet"' failed.
src\liboslexec\instance.cpp:494: RMAN_1697a56_OSL::pvt::ShaderInstance::copy_code_from_master: Assertion 'm_instoverrides.size() == (size_t)std::max(0,lastparam())' failed.
src\liboslexec\instance.cpp:480: RMAN_1697a56_OSL::pvt::ShaderInstance::copy_code_from_master: Assertion 'm_instops.empty() && m_instargs.empty()' failed.
src\liboslexec\instance.cpp:489: RMAN_1697a56_OSL::pvt::ShaderInstance::copy_code_from_master: Assertion 'm_instsymbols.size() == 0 && "should not have copied m_instsymbols yet"' failed.
src\liboslexec\instance.cpp:494: RMAN_1697a56_OSL::pvt::ShaderInstance::copy_code_from_master: Assertion 'm_instoverrides.size() == (size_t)std::max(0,lastparam())' failed.
S31020 {ERROR}   Inf/NaN detected in bounding of |walls_001|walls_001-MESH after displacement. Displacement will not be applied.
S31020 {ERROR}   Inf/NaN detected in bounding of |walls_001|walls_001-MESH after displacement. Displacement will not be applied.
S31020 {ERROR}   Inf/NaN detected in bounding of |walls_001|walls_001-MESH after displacement. Displacement will not be applied.
S31020 {ERROR}   Inf/NaN detected in bounding of |walls_001|walls_001-MESH after displacement. Displacement will not be applied.
S31020 {ERROR}   Inf/NaN detected in bounding of |walls_001|walls_001-MESH after displacement. Displacement will not be applied.
S31020 {ERROR}   Inf/NaN detected in bounding of |walls_001|walls_001-MESH after displacement. Displacement will not be applied.
S31020 {ERROR}   Inf/NaN detected in bounding of |walls_001|walls_001-MESH after displacement. Displacement will not be applied.
S31020 {ERROR}   Inf/NaN detected in bounding of |walls_001|walls_001-MESH after displacement. Displacement will not be applied.
S31020 {ERROR}   Inf/NaN detected in bounding of |walls_001|walls_001-MESH after displacement. Displacement will not be applied.

**Comment by prman-pixar** [comment]
@TzurH  I'll have to think about this. Blender doesn't seem to have a callback for when you link to an object, so we can't add the textures to the texture manager.

**Comment by TzurH** [comment]
I did some more tests and I've noticed this crash only occurs when I open scenes I had previously set up with materials, etc. which is probably why you aren't experiencing it?  If I start a new scene and then build the material from scratch it doesn't crash.

**Comment by TzurH** [comment]
I have shared a test scene with you on Goggle Drive. I've packaged this test scene using the new tool you've added. This scene is running fine on this commit:
https://github.com/prman-pixar/RenderManForBlender/tree/88c8b2ac3ef8f9f09811845585ec643c69d58184

Try to open it using the commits addressing this issue, it should crash.  Let me know if you need anything else to help test/debug.

**Comment by TzurH** [comment]
Can confirm works now. I'm also able to link collections which I was unable to do previously. Amazing! Thanks for the fix 💯
