### ISSUE TITLE
Posted about importing SVGs - No change with latest build

### ISSUE THREAD

**Issue by markartsf** [prman-pixar/RenderManForBlender#634]
I posted on Reddit about trying to extrude/lathe/revolve an imported SVG from Adobe Illustrator. I have installed the latest build and still appear not to be able to see an extruded curve without first converting it to a mesh.
<img width="2048" alt="Screen Shot 2021-11-04 at 12 35 54 PM" src="https://user-images.githubusercontent.com/3227868/140408178-f9bb143f-5ea5-461f-a050-147d9e1d7b7d.png">

**Comment by markartsf** [comment]
Actually I tried reinstalling the build and keeping the imported SVG's as curves does appear to be working in this build! Great work
<img width="2048" alt="Screen Shot 2021-11-04 at 12 54 26 PM" src="https://user-images.githubusercontent.com/3227868/140410812-1bfc6418-ffd7-4795-be7b-9332946568a6.png">
.

**Comment by prman-pixar** [comment]
@markartsf  Cool, glad the latest commit works for you. I'll mark this issue as closed.
