### ISSUE TITLE
IT - Auto Crop Render doesn't seem to work

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#635]
Hey Ian, hope you're well. Not many bug reports lately, that's a good sign! :)

I think this got broken once you've fixed #632 
If you use render region in IT IPR with Auto Crop Render toggled as opposed to Blender's render region, once you move back to Blender app, the IT render region doesn't "stick".

Here's a short capture to showcase what I mean
https://user-images.githubusercontent.com/10125645/140459953-395c2483-13f8-46bf-9426-5176861eb891.mp4

**Comment by prman-pixar** [comment]
@TzurH This is a bit confusing, and I'm not sure what the best way to solve this is. 

If you've drawn a render region and then draw a crop window in "it", which one do you want to take precedence? It doesn't seem like it makes sense to have both trying to do the same thing.

**Comment by TzurH** [comment]
@prman-pixar Yeah, I totally agree with you, there should only be one render region presence, either in Blender or in IT. That is what's actually being showcased in the video capture. Maybe it's unclear...

I only have a render region set in IT window, but as soon as I click on an object in Blender viewport, or get out of the current render camera view, the render region in IT doesn't take effect anymore.
It didn't use to behave like this in the past.

Hope this is clearer.

**Comment by prman-pixar** [comment]
@TzurH right, but I guess my question is: should we totally ignore the render region if you render to "it"? i.e.: would you expect "it" to only render the region you drew in the viewport on startup? What about if you remove the crop window in "it"; should we then reset to the render region that was drawn in the viewport?

I think I'd rather totally ignore render region when rendering to "it". That would make it easier to fix this, but I just wonder if Blender users would find that weird.

**Comment by TzurH** [comment]
@prman-pixar Hmm yeah, that's a bit of a UX dilemma... I'm not too sure what would be the best solution here.

The only thing I'd say is there are circumstances where using IT's render region is advantageous as it's always constrained to the render camera and so the user can still navigate the Blender scene.

**Comment by prman-pixar** [comment]
@TzurH  OK, I pushed a change for this. I sort of convinced myself over the weekend that we should just ignore the render region if you IPR to "it". You should just use the "it" crop window if you need to render a region.

**Comment by TzurH** [comment]
@prman-pixar Sounds good. Have juste tested and it works fine so closing this issue. Thanks for the fix!
