### ISSUE TITLE
how can i control color through density in volume rendering

### ISSUE THREAD

**Issue by Molers** [prman-pixar/RenderManForBlender#636]
hi everyone i want to implement fig1 with Renderman in Blender ,I'm not familiar with Renderman volume rendering and node system,could anyone help me?
![image](https://user-images.githubusercontent.com/23693269/140936465-feb7cf1f-043d-4090-a92e-9ac89395b4d9.png)
![image](https://user-images.githubusercontent.com/23693269/140936477-de97350f-bf40-409b-9c3d-c730850e94a6.png)

**Comment by prman-pixar** [comment]
Closing this as this is already posted on AnswerHub, and I don't think this is a bug.
