### ISSUE TITLE
Option to change default texture path to absoloute in prefs

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#637]
Could this be added, please?

Right now when we add a pxrTexture, we get a relative path by default, using the <blend_dir> token. That is problematic in some situations, would be good to have the ability in prefs to change this behavior.

For example, I work with this folder structure, where I have a layout scene that I **_only_** reference assets to. Each asset has its own .blend file. If I use the <blend_dir> token, texture paths get broken in the layout scene... I'm not sure why?
![image](https://user-images.githubusercontent.com/10125645/141242470-6c165f0f-4bb3-45c3-9b5d-d277df62aa0d.png)

To showcase, here's an asset I "append" with <blend_dir> tokens. All paths are broken.
![image](https://user-images.githubusercontent.com/10125645/141247971-7032bc80-70a4-4a97-a1bf-3a2aaadce9d7.png)

**Comment by prman-pixar** [comment]
So you just want a pref to always put in the real/absolute path?

**Comment by TzurH** [comment]
> So you just want a pref to always put in the real/absolute path?

Yeah, if that's doable.

**Comment by prman-pixar** [comment]
@TzurH I pushed a change for this. Let me know if it doesn't work for you.

**Comment by TzurH** [comment]
@prman-pixar Thanks for the fix! Works as expected.
