### ISSUE TITLE
PxrTexture breaks when material node has colon in name

### ISSUE THREAD

**Issue by breadbyte** [prman-pixar/RenderManForBlender#638]
Steps to reproduce:

1. Open blender.
2. Select the default cube.
3. Add a RenderMan nodetree to it. I used PxrDisneyBsdf as the material.
4. Add a PxrTexture node as the base color.
5. Add an image. It should appear.
6. Add a colon to the material name.
7. Change the image. Any changes to the image will not appear.
8. Remove the colon. An image must be set again for it to appear.

**Comment by prman-pixar** [comment]
Thanks for the report. We're currently using the material name as part an ID for the texture manager. Clearly this won't work if you rename the material. We'll have to come up with a better strategy for creating an ID for each texture in the texture manager.

**Comment by prman-pixar** [comment]
I believe I had a fixed this issue. Unfortunately, this is too late to get into the upcoming 24.3 release, but it will be available once 24.4 ships.

**Comment by fxjeane** [comment]
I just synced to the latest in master and I can see the issue when rendering with Blender 3.0.  The issue still happens whenever the material is renamed.

**Comment by prman-pixar** [comment]
Yes, it's a problem with some of the core python modules in PRMan.

**Comment by prman-pixar** [comment]
This issue should now be considered fixed with the release of RenderMan 24.4
