### ISSUE TITLE
<udim> token doesn't work when working with source file extension

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#639]
I get an error when I try to use the source file extension, in this example .exr. but it seems to work when I switch to the .tex files generated. does this only work with .tex?

I prefer to always point to the source file extension so when I do edits to the textures I don't have to manually reconvert the .tex, which saves time.

![image](https://user-images.githubusercontent.com/10125645/141393819-263e1fab-98ba-4913-9b0f-268eb5869c51.png)

.exr extension, I get an error
![image](https://user-images.githubusercontent.com/10125645/141393847-8af9433c-1c58-4f63-9f7f-91cf4a3fea87.png)

.tex is working fine
![image](https://user-images.githubusercontent.com/10125645/141393884-ebd87f66-6019-41cf-b064-94b65689c9bf.png)

**Comment by prman-pixar** [comment]
@TzurH  Can you see if the latest commit fixes this?

**Comment by TzurH** [comment]
@prman-pixar Fixed. Thank you. Only tested with .exr file extension. I assume will work with all files.
