### ISSUE TITLE
Blender for macOS ARM64 (Apple Silicon) Support

### ISSUE THREAD

**Issue by mrandd** [prman-pixar/RenderManForBlender#641]
On the Blender for Apple Silicon build, I can't activate the plugin.
I was able to activate it on the Intel Build (using Rosetta) and it now appears in my ARM Blender Version, but it doesn't do anything.
Is this an issue with Blender or would the plugin require its own ARM64 Build?
Renderman itself seems to work fine (I assume using Rosetta).

Thanks!

**Comment by prman-pixar** [comment]
The latter most likely. I think the first hurdle would be needing to recompile our python modules to ARM64, but I'm just guessing.
