### ISSUE TITLE
Bump 2 Roughness conversion

### ISSUE THREAD

**Issue by TzurH** [prman-pixar/RenderManForBlender#642]
I've just started exploring Bump 2 Roughness, when I use TX Manager for the conversion, I use the following settings
![image](https://user-images.githubusercontent.com/10125645/144367608-f6f670d8-86d3-41e1-b578-1d01562f0583.png)
After I hit apply and wait for the conversion to finish, TX Manager is showing me the following:
![image](https://user-images.githubusercontent.com/10125645/144367724-995cb3ca-1598-483d-be8b-592533f9a1b3.png)

I'm not sure why the following settings are now checked? I didn't check them when making the conversion (see the first picture)
Is it a visual bug or does it actually affect the texture? Is there a way to see the command (tx make) used? If it does affect the texture, then that could lead to the wrong result?
![image](https://user-images.githubusercontent.com/10125645/144367838-01f28c75-3800-4c13-bce4-d7ca403b4d2a.png)

**Comment by prman-pixar** [comment]
@TzurH  yeah, looks like this was a visual bug. Can you see if the latest commit fixes it for you?

**Comment by TzurH** [comment]
@prman-pixar yeah, that fixed it. thank you! closing this.
