### ISSUE TITLE
Encountered a problem while rendering.

### ISSUE THREAD

**Issue by SMALLAOLYY** [prman-pixar/RenderManForBlender#643]
![WEKEOKWGI)}EB%%%HE2$B%4](https://user-images.githubusercontent.com/55980673/144735827-af220539-53b4-4d40-810d-dfcceb89ee84.png)
I dont know how to do.
RAM 32G  Video memory 6G.

**Comment by prman-pixar** [comment]
Closing, as we were able to solve this on GitHub.

https://renderman.pixar.com/answers/questions/23855/why-does-blender-crash-when-i-render.html
