### ISSUE TITLE
Error In RMANTREE

### ISSUE THREAD

**Issue by RevenantArts** [prman-pixar/RenderManForBlender#645]
hello! I'm fairly new to using render man and after installing it I get the following error
![image](https://user-images.githubusercontent.com/98871185/152107756-8fb594cd-f5e2-4311-aaf0-924fa9a9e4a0.png)
is there any way to fix this?

**Comment by prman-pixar** [comment]
Have you installed RenderMan Pro Server as well? What OS are you using?

**Comment by RevenantArts** [comment]
I havent installed Renderman pro server, and windows 10

**Comment by prman-pixar** [comment]
You need to install RenderMan Pro Server, or else the addon won't work. If you're trying to use non-commrercial RenderMan, you can download RenderMan Pro Server along with a license here:

https://renderman.pixar.com/intro

**Comment by prman-pixar** [comment]
@RevenantArts are you still having trouble with this?

**Comment by RevenantArts** [comment]
Ah forgive my lack of a response. I got it figured out, Thank you :)

**Comment by MaximLyalin2002** [comment]
У меня аналогичная проблема.
Установлен RenderMan Pro Server с официального сайта.
Установлен RenderMan Pro Server 25, ОС Windows 10.
![1](https://user-images.githubusercontent.com/123141603/233811614-b6b1f65d-ef5b-406d-b513-3484b4624006.png)
![2](https://user-images.githubusercontent.com/123141603/233811615-844e4420-4a6c-4748-a3ab-d5cb60cc0f26.png)
