### ISSUE TITLE
Light wireframes are still drawn when overlays are turned off

### ISSUE THREAD

**Issue by mmdanggg2** [prman-pixar/RenderManForBlender#646]
When you disable overlays, I would expect the light wireframe representations to also be disabled.
![image](https://user-images.githubusercontent.com/3161587/155867821-ca6414dd-02dd-4985-9d0d-a3df58e3ac08.png)

The z occlusion of the wireframes also becomes frozen/incorrect while show overlays is disabled and viewport rendering:

https://user-images.githubusercontent.com/3161587/155868484-5ea45441-bb29-4830-ab44-c7f85e91ddf0.mp4

**Comment by prman-pixar** [comment]
@mmdanggg2  can you see if the latest commit fixes the problem of the wireframes still being drawn when overlays are disabled?

Not sure about the z occlusion issue. I'm not seeing that.

**Comment by mmdanggg2** [comment]
Yep, that did the trick! Thanks for the quick response. I suppose the occlusion thing is irrelevant if they're hidden.

One related suggestion, it would be nice if the wireframe could be used to select the light. Would just make it a little easier to select them and bring it more in-line with the blender lights.
![image](https://user-images.githubusercontent.com/3161587/156081569-e52bf134-d7fb-4972-9b94-e0f7df4cfe0a.png)
eg. doing a box select, the default blender light (left) would be selected, the renderman one won't despite being within the box.

**Comment by prman-pixar** [comment]
@mmdanggg2 Great! 

re: box select

Yes, that bothers me as well. Unfortunately, Blender doesn't seem to expose an API to get a callback when a box select is drawn.
