### ISSUE TITLE
MaterialX  ?

### ISSUE THREAD

**Issue by schulze1963** [prman-pixar/RenderManForBlender#654]
Is it somehow possible to put MaterialX materials (for example from https://matlib.gpuopen.com) in
Invite RenderManForBlender?

**Comment by bsavery** [comment]
Sorry to jump in...
@schulze1963 the other way you can do this currently is to use the Hydra add-on for Blender. https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon which connects up the materialX library to Blender and also supports the RenderMan Hydra delegate.  

We actually did test MaterialX materials rendering inside blender that way to RenderMan, so it should work.
