### ISSUE TITLE
manta flow Render problem

### ISSUE THREAD

**Issue by stevensen4** [prman-pixar/RenderManForBlender#655]
Hello,
I am not an expert in Blender 2.93 and Renderman 24.4.
Nevertheless I wanted to render a small Mantafuid simulation with Renderman, but unfortunately I can't get it to work.
Maybe I'm doing something wrong or maybe it's a bug
First renderd in cycles
![Fluid_cycles](https://user-images.githubusercontent.com/109481194/179710329-229ccf90-a7fb-464a-acb8-e80f887d4437.png)

Renderd ( or not ) in Renderman:
![Fluid_Renderman](https://user-images.githubusercontent.com/109481194/179710338-6ac2b5f5-c6ee-437e-81c7-8d6b6a99dd9c.png)
[liquid_problem_blendfile.zip](https://github.com/prman-pixar/RenderManForBlender/files/9139225/liquid_problem_blendfile.zip)
.

**Comment by prman-pixar** [comment]
@stevensen4  can you give the latest commit into a dev branch a try, and see if that works for you?
