### ISSUE TITLE
renderman render black

### ISSUE THREAD

**Issue by deboi238** [prman-pixar/RenderManForBlender#660]
when i render renderman it shows black screen

**Comment by deboi238** [comment]
using blender 3.0 
renderman (dev branch)

**Comment by deboi238** [comment]
and having this error 
Export failed: 'TokenTable' object has no attribute 'k_hider_bakeudimstride'

**Comment by deboi238** [comment]
![0001](https://user-images.githubusercontent.com/90112349/191899701-b026b9d1-258a-4aa3-9b67-4c99c7ee1a47.png)

this is the render too

**Comment by prman-pixar** [comment]
How are you rendering? IPR?  Render->Render Image? It's strange you're getting that error, because you would only go down that code path if you're doing baking.

**Comment by deboi238** [comment]
@prman-pixar im using it, when i use blender it shows same results

**Comment by deboi238** [comment]
i see the preview image in the render tab but dont see anything in the video file

**Comment by prman-pixar** [comment]
@deboi238  Video? I'm not sure what you mean by video.

**Comment by deboi238** [comment]
when I set blender the render file, i set it to mkv or avi, i still dont see anything.

**Comment by prman-pixar** [comment]
@deboi238  we don't support rendering to mkv or avi directly.

**Comment by deboi238** [comment]
Weird that it works before but it renders nothing? If I use png still
doesn't work

**Comment by prman-pixar** [comment]
I'm not sure. I've never tried rendering to mkv or avi directly in Blender. RenderMan itself doesn't render to those formats; it only renders images. Blender could be assembling the images and rendering an AVI for you, but I've never looked into that before. 

Note, if you're rendering to "it", there is no image on the disk. You have to manually save the image out.

**Comment by deboi238** [comment]
Ok, although I’m still wondering why I’m still getting black picture/video
results

**Comment by prman-pixar** [comment]
Not sure. Can you check the alpha? Just want to distinguish between if the objects are there or not.

**Comment by deboi238** [comment]
How can I chec the alpha

**Comment by deboi238** [comment]
and i have new problem, now when i set render to blender, it stuck at 0% render and if i cancel it, it stays at 0%

**Comment by prman-pixar** [comment]
@deboi238  I meant just looking at the alpha channel. If you render to "it" and press "G" on the keyboard, that will show the alpha channel.

Not sure about the render being stuck at 0%. I would need a scene file to investigate.

**Comment by deboi238** [comment]
By I mean it at 0%, when I render to blender, the render percentage will be
stuck at 0%, and when I try to cancel it, blender will freeze on me.

**Comment by deboi238** [comment]
@prman-pixar i figured out whats wrong, something is wrong with the dev branch, if i use the main branch it renders fine

**Comment by deboi238** [comment]
never mind since it broked on me again

**Comment by deboi238** [comment]
im confused if i change resolution under baking it fixes the problem

**Comment by deboi238** [comment]
and the dev/main branch keep crashing on me within 5 min rendering

**Comment by prman-pixar** [comment]
@deboi238  Can you please provide an example file? It's hard to debug this if I can't reproduce this myself, or see any debug logging.

**Comment by prman-pixar** [comment]
Also, can you also mention what operating system you're using etc.

**Comment by deboi238** [comment]
using windows 10 64 bit
hardware is
AMD RYZEN 5 5600X
GTX 1060 6GB
48 GB RAM

**Comment by prman-pixar** [comment]
@deboi238 Thanks. Can you give me an example .blend file?

**Comment by deboi238** [comment]
@prman-pixar **testing light**
[untitled.zip](https://github.com/prman-pixar/RenderManForBlender/files/9679570/untitled.zip)

**Comment by deboi238** [comment]
it keep crashing while i tried turning down the thread/change the bucket size 8x8 to 64x64, and more

**Comment by deboi238** [comment]
I fixed the black screen problem but the rendering keep crashing within 15-50 frames

**Comment by prman-pixar** [comment]
@deboi238  I'm not seeing a crash with your scene, but I've only tried it with IPR. When you say it crashes within 15-50 frames, are you talking in an animation render i.e.: you're doing Render->Render Animation?

**Comment by deboi238** [comment]
Yea it render with render animation but crashes with blender

**Comment by deboi238** [comment]
@prman-pixar it keep crashing around 35 frames, im using render-> render animation with blender optix de noising

**Comment by prman-pixar** [comment]
@deboi238 Can you try it without the Optix denoiser turned on, and see if that works? I haven't got it to crash, but I did notice that the memory slowly climbs with each frame, so there could be a memory leak somewhere. 

Also, if you do want to render an animated sequence, I would suggest looking at external (batch) rendering.  

https://rmanwiki.pixar.com/display/RFB24/Batch+Rendering+in+Blender

**Comment by deboi238** [comment]
@prman-pixar weird, i turned off the optx denoiser and it dosent crash, i notice it climbed max 3 GB ram

**Comment by prman-pixar** [comment]
@deboi238 OK, thanks. I'll see if I can figure out where the leak is happening, but, for now, I would suggest using batch rendering if you need to render animations.

**Comment by deboi238** [comment]
it still keep crashing with optx, same goes with batch rendering

**Comment by prman-pixar** [comment]
@deboi238  It's the same problem where it crashes around frame 15-50? What happens if you switch "Spool Style" to "RIB" in the spool options?

**Comment by deboi238** [comment]
@prman-pixar when i click external rendering it dosent do anything

**Comment by prman-pixar** [comment]
@deboi238 Is there any error messages in the console window?

**Comment by deboi238** [comment]
No

**Comment by deboi238** [comment]
@prman-pixar theres no errors and nothing pops up for anything

**Comment by prman-pixar** [comment]
@deboi238  I can't reproduce what you're seeing. If you have a different .blend file I can test with, can you please provide it? Also, please include the textures as well.

**Comment by deboi238** [comment]
[untitled. 2blend.zip](https://github.com/prman-pixar/RenderManForBlender/files/9815888/untitled.2blend.zip)

ok, i made another that also keep crashing on me

**Comment by prman-pixar** [comment]
@deboi238  Your zip doesn't include the textures. Can you please include the textures? Also, your scene has spaces in a lot of the paths, including the blend file itself (ex: C:/Users/edwin/Downloads/gtag stuff/...). 

Can you try replacing all the spaces with underscores, and see if that fixes things?

**Comment by deboi238** [comment]
I packed the textures in the .blend, if you still have missing textures I
can send it to you

**Comment by deboi238** [comment]
so turns out optix is using my cpu alot and keep crashing it

**Comment by prman-pixar** [comment]
@deboi238 I only see a bunch of Diffuse_* textures packed with the scene. I'm missing:

C:/Users/edwin/Downloads/gtag stuff/GameObject/cosmeticsroomatlas.png
D:\a fukkkakakakakaka\saved tings\textures\cosmeticsroomatlas.png

Did you also try my suggestion of not using spaces in your file paths?

Finally, are you saying it doesn't crash if you use OptiX denoiser? If so, like I said earlier, there seems to be a  memory leak when using the OptiX denoiser, that might lead to a crash. I believe I fixed it, if you want to give it a try. 

Download the attached file:

[d_blender.zip](https://github.com/prman-pixar/RenderManForBlender/files/9841178/d_blender.zip)

Unzip it, and copy it to C:\Program Files\Pixar\RenderManProServer-24.4\lib\plugins. You'll want to make a backup of the old version, in case something goes wrong.

**Comment by deboi238** [comment]
@prman-pixar so the missing files you said 
"C:/Users/edwin/Downloads/gtag stuff/GameObject/cosmeticsroomatlas.png
D:\a fukkkakakakakaka\saved tings\textures\cosmeticsroomatlas.png" 
it's like that for me but it wouldn't effect it, it crashed when I use Optix denoiser. the file you sent worked but the memory leak got worse, the file i sent to you, it climbed to 12 GB of ram. it slowly climbed 1 GB every 10-20 frames

**Comment by deboi238** [comment]
but i got enough ram to render it out but thanks
