### ISSUE TITLE
Blender 3.4 support

### ISSUE THREAD

**Issue by Bil97** [prman-pixar/RenderManForBlender#666]
The plugin does not work in blender 3.3 or 34.

Here is the error message:
![image](https://user-images.githubusercontent.com/36190575/217190026-15f05027-e45b-428d-b7bf-8b9b59c62610.png)

**Comment by prman-pixar** [comment]
Yes, we currently do not support Blender 3.3 or 3.4, as they require python 3.10 (we currently only support python 3.9). Your only choices are either:

1. Wait for RenderMan 25.
2. Compile Blender 3.4 yourself using python 3.9
3. There are unofficial builds of Blender 3.3 that are built with python 3.9. However, we don't officially support these, but they should work: https://blender.community/c/graphicall/dwKJ/?sorting=hot

**Comment by Bil97** [comment]
The builds did not help. I will just wait for version 2.5. when is it being released?
