### ISSUE TITLE
Difficulty Switching User Libraries in the Qt UI Preset Browser

### ISSUE THREAD

**Issue by CurbaiCode** [prman-pixar/RenderManForBlender#668]
There is no `Select Library` option or equivalent in the Qt UI Preset Browser.

When I use the new Qt UI Framework for the Preset Browser in RenderMan 25, the only way I've found to change the displayed user library is to use the `Libraries > Add Library...` item and pick the location of one of my asset libraries. This takes a while to load, though one of my libraries is large enough to cause Blender to stop responding. Using the Native UI Framework, I am able to use `Select Library` and quickly switch between them with the dropdown.

Environment:

 * UI Framework = Qt
 * Use WIP UI = false
 * RenderMan 25.0
 * Blender 3.3.5 (Python 3.9)
 * macOS 12.6

**Comment by prman-pixar** [comment]
You switch between Libraries in the View menu. But you have to add the library using Libraries > Add Library before they show up in the View menu. Are you saying that you're not seeing the libraries in the View menu after adding them?
If you also added the library in the native framework, they should up in the View menu in the Qt version as well.

**Comment by CurbaiCode** [comment]
Thank you @prman-pixar, I am now able to switch between my libraries using the `View` menu, but only after I added them with the Qt Preset Browser. This was even if I had already added them with the Native Preset Browser. However, if I remove them from the Qt Preset Browser, they are also removed from the Native Preset Browser. Also, if I remove the library from the Native Preset Browser, then they are still in the Qt Preset Browser.

So it seems like adding/removing libraries in in the Qt Preset Browser changes it globally, while the Native Preset Browser only affects itself.

Thank you again.

**Comment by prman-pixar** [comment]
OK, thanks. I think that sort of makes sense, as I don't believe the Qt preset browser will re-read the prefs on each opening, so it's just showing the libraries it has in cache. In any case, the plan is to remove the native one, eventually, and only have the Qt one.
