### ISSUE TITLE
"error in rmantree"

### ISSUE THREAD

**Issue by Starcle3D** [prman-pixar/RenderManForBlender#669]
![152107756-8fb594cd-f5e2-4311-aaf0-924fa9a9e4a0](https://user-images.githubusercontent.com/131329174/233253084-02473c3e-b0fa-4d88-981a-172a21c493b8.png)
Hello,
I have this error in BLENDER and have installed  the RenderManProServer-25.0 .  But work fine in Maya. I use win10 Can you help?

**Comment by 0x384c0** [comment]
Which Blender version do you use?
It is possible to get this error on unsupported versions of Blender like 3.5
You can also see this error in Blender  system console
`[ERROR] (MainThread) RenderManForBlender.rfb_logger _guess_rmantree: The Python version this Blender uses (3.10) is not supported by this version of RenderMan (25.0)`

**Comment by prman-pixar** [comment]
Yes, Blender 3.5 is not currently supported. We are trying to add support for it for the next dot release (25.1).

**Comment by ksantiago1974** [comment]
![BlenderRenderman25](https://user-images.githubusercontent.com/68402856/233524662-fa669a4d-6b49-4afd-8585-0656c03884d1.png)

Same thing happens with Blender 3.40

**Comment by prman-pixar** [comment]
@ksantiago1974  Blender 3.4.0 is not supported. The highest we support 3.0.1, and is mentioned in the docs:

https://rmanwiki.pixar.com/display/RFB25/Installation+of+RenderMan+for+Blender

**Comment by prman-pixar** [comment]
We now support Blender 3.5. Please upgrade to RenderMan 25.1 in order to use it with Blender 3.5.

**Comment by nixa3d** [comment]
yo l omismo... con la 4.2
