### ISSUE TITLE
No Intel Arc A750/770 XPU Support

### ISSUE THREAD

**Issue by MikelMNJ** [prman-pixar/RenderManForBlender#671]
Hello,

I know they are still new and young, but their hardware has been fantastic in other productivity suites so far.  Can we build in support in a future dot release for XPU rendering with these cards?  Especially with their more kid and high tier cards coming in the future.

Im not an expert, but hoping their Xe cores function similarly to Nvidia’s?

Mikel

**Comment by prman-pixar** [comment]
We are always looking and evaluating new hardware. However, we don't have anything to announce about Intel Arc support at this point.
