### ISSUE TITLE
Add Channel dropdown missing from AOV passes

### ISSUE THREAD

**Issue by jdent02** [prman-pixar/RenderManForBlender#674]
![image](https://user-images.githubusercontent.com/13521172/236374608-5f5db2b8-bb2e-4db4-bc04-8d28d8003681.png)

using Renderman 25.0 Release.

Windows 10

**Comment by jdent02** [comment]
Update: Restarted Blender with a new scene and now all of a sudden the menu appears.

**Comment by prman-pixar** [comment]
@jdent02  that's weird. If it happens again and you have a way of reproducing it, let us know.
