### ISSUE TITLE
Lens shift settings from active camera also apply to viewport IPR renders outside of camera

### ISSUE THREAD

**Issue by tim-3d** [prman-pixar/RenderManForBlender#677]
Hi!

I noticed today that the Lens Shift X/Y values set in the active blender camera get applied to the whole image when rendering from regular perspective viewport, (outside of viewing through the camera)

(It'll render correctly when looking through the camera though, matching the viewport)

here's the lens Shift options in blender camera:
![image](https://github.com/prman-pixar/RenderManForBlender/assets/9963530/02de1e26-430f-4e23-83d8-1313ff1927ee)
example screenshot, the cube gets rendered a little to the left as per the lens offset settings
![image](https://github.com/prman-pixar/RenderManForBlender/assets/9963530/975c7a69-50bd-4547-bdf5-587a0134a136)

I'm using renderman ncr 25.1 with blender 3.3.6 LTS
on Windows 10 22H2

let me know if you need any more info etc.

Cheers,
Tim

**Comment by prman-pixar** [comment]
Thanks for the report. Can you see if the latest commit in the dev branch fixes the problem for you?

**Comment by tim-3d** [comment]
Yes, this fixes the issue! Thank you!
