### ISSUE TITLE
MaterialX

### ISSUE THREAD

**Issue by schulze1963** [prman-pixar/RenderManForBlender#679]
On the website https://matlib.gpuopen.com/main/materials/all there are many ready-made materials according to the materialx industry standard. Is there a way to use these materials directly in Renderman for Blender?

**Comment by prman-pixar** [comment]
Unfortunately, RenderMan does not currently support MaterialX directly. It is on our roadmap to support in the future, though.

**Comment by schulze1963** [comment]
many thanks for the quick response. I hope that this feature can be implemented soon
