### ISSUE TITLE
Renderman Render Error Blender

### ISSUE THREAD

**Issue by Rafael282828** [prman-pixar/RenderManForBlender#680]
When rendering, I get the following error:
Export failed bpy_prop_collections[indez]: index 16448 out of range, size 5.
![image](https://github.com/prman-pixar/RenderManForBlender/assets/65774986/17e9b6c8-0f88-4918-aa3b-bc6082ac4b90)
Could someone help me solve it?

**Comment by prman-pixar** [comment]
@Rafael282828  Do you mind attaching the blend file you're using?

**Comment by prman-pixar** [comment]
@Rafael282828  pinging one more time. Can you provide a blend file that shows the issue?

**Comment by prman-pixar** [comment]
No response. Closing.
