### ISSUE TITLE
Black Texture

### ISSUE THREAD

**Issue by MiyajiAnimation** [prman-pixar/RenderManForBlender#685]
Aw. Why the black?
And i don't know how to fix the black?
![Screenshot (1260)](https://github.com/prman-pixar/RenderManForBlender/assets/142801625/4bc9b8fe-7f59-4dab-ab2e-8fbd55d0203a)

**Comment by prman-pixar** [comment]
It's really hard to see your shading network from your image, but if your textures include an alpha, and you want the alpha to cut through, connect resultA from PxrTexture to the Presence input on the LamaSurface node (assuming you're using Lama). resultA is the alpha from your texture; resultRGB is just the RGB channels of your texture.

**Comment by MiyajiAnimation** [comment]
Aw thank for you the helping.
