### ISSUE TITLE
Split view and Blender unresponsive upon dragging window border in Blender on XPU mode enabled viewport render.

### ISSUE THREAD

**Issue by markidak** [prman-pixar/RenderManForBlender#687]
![image](https://github.com/prman-pixar/RenderManForBlender/assets/33268307/d5b54cb8-358c-4b89-85fa-7a57c746b6ea)

**Comment by prman-pixar** [comment]
Can you see if you get the same problem if you use the dev branch?

https://github.com/prman-pixar/RenderManForBlender/tree/dev

I did fix an issue where it would stall if you resized the windows.

**Comment by prman-pixar** [comment]
No response in almost two months. Closing.
