### ISSUE TITLE
Freezes if Renderman license in invalid

### ISSUE THREAD

**Issue by erjiang** [prman-pixar/RenderManForBlender#688]
Renderman for Blender freezes when trying to render if the rman license is invalid.

To reproduce:
* Change rman node ID so that the non-commercial license is invalid (by changing a network interface mac address, for example)
* Create a new Blender scene and change renderer to Renderman
* Try to render

Expected:

An error should be displayed somewhere in Blender with the Renderman error.

Actual:

Blender hangs

Renderman for Blender 25.2.0
Blender 3.6.2
OS: Linux

**Comment by prman-pixar** [comment]
@erjiang 

This is a known issue. We currently don't have python bindings to specify an error handler when the renderer exits because of a license issue.

Is there a reason why you're trying to directly modify the license file?

**Comment by erjiang** [comment]
> Is there a reason why you're trying to directly modify the license file?

I wasn't modifying the license file. I was trying to figure out why Renderman was not working even though I had a license. The issue was that having Docker installed will change the Renderman license node ID every reboot, but I didn't get an error message about the license in the Blender UI.
