### ISSUE TITLE
Object exports with another object's geometry

### ISSUE THREAD

**Issue by erjiang** [prman-pixar/RenderManForBlender#696]
I have a scene where when I render with Renderman, one of the objects incorrectly uses another object's geometry instead of its own geometry. I can share the scene if you can send me a link to where you want me to upload the file (email is on my Github profile).

**Comment by prman-pixar** [comment]
@erjiang 

You should be getting an e-mail with a BOX folder link shortly. Please upload this one and the one for #692 .

**Comment by erjiang** [comment]
I have uploaded "painter9-buggy.blend", which should demonstrate both this issue and #692.

1. In IPR, object "ceramic2" and "ceramic8" take on the geometry of "tarp2"
2. Object "Split Diopter" triggers issue #692 (but I think #695 fixes that problem)

**Comment by prman-pixar** [comment]
Thanks. I will merge in your change for the index error.

With regards to this issue, are you on Windows? If so, do you have "GPU Subdivision" turned on? If it's on, try turning it off and see if you get the right render.

If you do get the right render, this is a bug on the Blender side (https://projects.blender.org/blender/blender/issues/111393). I committed a workaround fix for it, though, so double check to see if your local version has my change:  https://github.com/prman-pixar/RenderManForBlender/commit/8fe492fda06ca8da6f800e2977ac17d354b34683

**Comment by erjiang** [comment]
> With regards to this issue, are you on Windows? If so, do you have "GPU Subdivision" turned on? If it's on, try turning it off and see if you get the right render.

Makes sense, the problem objects all had a subdivision modifier. I am on Linux and turning off GPU subdivision does fix the issue.

> If you do get the right render, this is a bug on the Blender side (https://projects.blender.org/blender/blender/issues/111393). I committed a workaround fix for it, though, so double check to see if your local version has my change: https://github.com/prman-pixar/RenderManForBlender/commit/8fe492fda06ca8da6f800e2977ac17d354b34683

The dev branch also does not have this problem.
