### ISSUE TITLE
Adding RenderMan lights does not respect cursor and collection

### ISSUE THREAD

**Issue by erjiang** [prman-pixar/RenderManForBlender#700]
When adding objects in Blender via the Shift-A Add menu, the new object should be placed at the 3D cursor location and in the active collection. RfB instead places them at the world origin and in the Scene collection.

To reproduce:

1. Create a new collection and mark it as active.
2. Move the 3D cursor to a location different from world origin.
3. Shift-A -> RenderMan -> Light -> PxrRectLight

Expected:

PxrRectLight should  be created at the 3D cursor location in the new collection.

Actual:

PxrRectLight is created at 0,0,0 in the Scene Collection

**Comment by prman-pixar** [comment]
Should be fixed now.

**Comment by erjiang** [comment]
Looks like latest revision on dev does put lights at the 3d cursor but doesn't seem to put them in the selected collection by default.
