### ISSUE TITLE
Hiding an empty also hides its children in IPR

### ISSUE THREAD

**Issue by erjiang** [prman-pixar/RenderManForBlender#702]
In Blender, hiding an empty object should not hide its children. This is true for the Blender viewport and built-in renderers. In the RenderMan IPR, hiding an empty will cause its children to also be hidden, sometimes unpredictably.

To reproduce:

1. Create an empty.
2. Create a cube.
3. Make the empty the cube's parent.
4. Start IPR
5. Hide the empty

Expected:

Cube should remain visible

Actual:

Cube disappears

**Comment by erjiang** [comment]
Sometimes the children of hidden empties will show up when IPR is started, then disappear when IPR is updated.

**Comment by prman-pixar** [comment]
I will try address this for RenderMan 26. I think this will require a larger change that I'm not comfortable pushing back to the current dev branch.

**Comment by prman-pixar** [comment]
This should be fixed now. However, as I said earlier I'm probably not going to push it back to the current dev branch as it's quite a large change.
