### ISSUE TITLE
Can't install latest release in Blender 4.1

### ISSUE THREAD

**Issue by GlacierFox** [prman-pixar/RenderManForBlender#707]
I can't seem to install the latest version (26.1) of the add-on in Blender 4.1 using Renderman 26.1 on Linux. I'm notified that the add-on is in fact installed but I can't enable it.  Sorry I can't copy and paste the output from the window and I'm not sure where the log goes so here's an image of the error.

![image](https://github.com/prman-pixar/RenderManForBlender/assets/9074086/098eea38-d697-4d92-b6ac-2f02b6ca714f)

I've tried literally deleting my entire Blender installation and trying on a fresh copy but still getting the same result. I've also deleted any old data in my local .config/blender folder too.

I'm able to install the previous 26.0 release however but I'm not sure this is compatible with the 26.1 RenderMan version I've got installed on my machine?

![image](https://github.com/prman-pixar/RenderManForBlender/assets/9074086/e47b7135-47a5-4b01-8ce7-8ad28d1710b3)

**Comment by ASCUG** [comment]
I'm having a similar issue on Mac. However, I tried the earlier release and get the same error message when I try to enable 26.0.
![Screenshot 2024-05-07 at 9 44 59 PM](https://github.com/prman-pixar/RenderManForBlender/assets/161161232/62d99da0-d2bf-4a80-ba5f-6a9f99cf22f5)

**Comment by Youplee66** [comment]
Hello, I had the same issue on Fedora. Solved by the following command : 

sudo dnf install ncurses-compat-libs.x86_64

source : Renderman Discord channel

**Comment by prman-pixar** [comment]
@GlacierFox 

Where did you download the addon? The module name looks a little oddly named (it says RenderManForBlender-v_26 in your screenshot)

@ASCUG  

Make sure that you downloaded and installed the Intel version of Blender. We currently do not support the M2 version of Blender, on the mac.

**Comment by GlacierFox** [comment]
@prman-pixar

I downloaded it from the releases section on here, the most recent 26.1 version of the addon, then installed it directly in Blender.

The previous 26.0 version below it works fine as you can see from the above image but I get that error after installing the 26.1 version.

**Comment by prman-pixar** [comment]
@GlacierFox 

Try renaming that directory to just RenderManForBlender instead of RenderManForBlender-v_26.1. i.e.: the one in /home/danny/.config/blender/4.1/scripts/addons/

**Comment by GlacierFox** [comment]
> @GlacierFox
> 
> Try renaming that directory to just RenderManForBlender instead of RenderManForBlender-v_26.1. i.e.: the one in /home/danny/.config/blender/4.1/scripts/addons/

Yes! Thats it. After it seems to be working now.

Looks like the addon is being extracted with the incorrect folder name when installing through the Blender preferences menu as instructed. Not sure why that's happening.

**Comment by prman-pixar** [comment]
@GlacierFox  great, glad it's working now.

@ASCUG can you confirm that you're using the Intel version of Blender, on your Mac?

**Comment by ASCUG** [comment]
Yes, it does work on the intel version. 
Are there any rumblings of the plugin being supported on M series chips in upcoming releases?
