### ISSUE TITLE
Crash Core Dumped in Centos 8 with 26.1 renderman

### ISSUE THREAD

**Issue by arnabiitr** [prman-pixar/RenderManForBlender#710]
Crash Core Dumped in Centos 8 with 26.1 renderman

**Comment by prman-pixar** [comment]
@arnabiitr We just released RenderMan 26.2 which, theoretically,  should work with CentOS8 . If you can give it a try and report back whether or not it worked for you that would be great.

**Comment by prman-pixar** [comment]
No response in over three weeks. Closing.
