### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by djjcyang** [prman-pixar/RenderManForBlender#711]
Blender ver4.2.3

Error:Errorin RMANTREE. Reload addon to reset.

The Environment Variable setted defult, renderman server installed defult.
![image](https://github.com/user-attachments/assets/022a6e3d-5b76-469c-a21c-6f6aa1e79c3e)

Try to delete all addons except renderman for blender, instalation fail.
Try to different blender version 4.3 3.6 ,instalation fail.
What can I do now?

**Comment by prman-pixar** [comment]
Did you install RenderMan Pro Server? The addon needs that in order to function. 

https://rmanwiki-26.pixar.com/space/RFB26/20086854/Installation+of+RenderMan+for+Blender

**Comment by prman-pixar** [comment]
Closing. No response in over two weeks.
