### ISSUE TITLE
DoF Roundness and Density only go from 0 to 1 instead of -1 to 1

### ISSUE THREAD

**Issue by Corefrecs** [prman-pixar/RenderManForBlender#714]
"Roundness" and "Density" in Camera DoF settings only go from 0 to 1 instead of -1 to 1.
Ref.:
[Renderman Blender Wiki](https://rmanwiki-26.pixar.com/space/RFB26/20086871/Depth+of+Field+in+Blender)
[Renderman Wiki Bokeh](https://rmanwiki-26.pixar.com/space/RFH26/19267659/Bokeh)

I think the values get clipped in:
[rman_properties_camera.json](https://github.com/prman-pixar/RenderManForBlender/blob/main/rman_config/config/rman_properties_camera.json)

**Comment by prman-pixar** [comment]
Thanks for pointing this out. I'll try to fix in the next couple of days.

**Comment by prman-pixar** [comment]
Should be fixed now.
